### ISSUE TITLE
SDWebImageManager uses DISPATCH_QUEUE_PRIORITY_HIGH and downloadOperationQueue is redundant

### ISSUE THREAD

**Issue by wangjufan** [SDWebImage/SDWebImage#2268]
There are two points here ,
first ,  dispatch does need many system resources than known usually ;
second ,  DISPATCH_QUEUE_PRIORITY_HIGH is not a good choice for many apps .

I suggest we should remove the dispatch here to give as many resources as we can to UI threads
or use default priority to  increase downloading concurrency . 

And i found  NSOperaton was used to wrap a download task ,  but NSUrlsession has provide the operation queue in itself without  NSOperaton ,  so code redundency exist .

**Comment by dreampiggy** [comment]
Since a project last 4 years. There are not always can done the best practice.

The first one, about `DISPATCH_QUEUE_PRIORITY_HIGH`. There are only two entry for this usage. One is the custom image transformer feature, and another is the cache serializer.
Both of these two are used as optional, So that means if you don't provide one, there is no cost for this. And since image transformer is about image processing (Most of it work is vertex calculation); The cache serializer is about image encoding (happened in memory too). They are not so so time-consuming like network request. So I think we set QoS to High is OK.

If you're really care about the performance. In 5.x, you can totally create your own implementation besed on #2256.

**Comment by wangjufan** [comment]
It is my pleasure .  I will try my best to do it  in the coming month .

**Comment by bpoplauschi** [comment]
Closing the issue per lack of activity. @wangjufan if you are still interested in this subject, please reopen/comment/create PR ...
