### ISSUE TITLE
No Request Header with different token in images request - Critical

### ISSUE THREAD

**Issue by ankitherocker** [SDWebImage/SDWebImage#232]
this is an awesome component! I have heavily used it in my app! but now I am facing a major issue, my webservices are now secured with request headers with different token every time & I find no way to pass them a different token in every image request based on user's username password generated token. This is very critical for me! And I don't want to use any othr plugin other than urs' wonderful plugin. Would be so glad if you can help me asap.

Thanks In Advance.

**Comment by DylanVann** [comment]
The problem is that @ankitherocker wants each SDWebImage request to specify its own headers.

As it is headers are not associated with requests, they're shared between all requests for a downloader.

Same issue:

https://github.com/rs/SDWebImage/issues/729
https://github.com/rs/SDWebImage/issues/166#issuecomment-8379698
