### ISSUE TITLE
iOS 12  NSLocalizedDescription=已取消} [-999]

### ISSUE THREAD

**Issue by JKjiangnan** [SDWebImage/SDWebImage#2492]
在iOS12 上使用http 或 使用SDWebImageRefreshCached  的时候会频繁出现
_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <2598BFA1-B359-4A5D-964D-AB00F62F3D1E>.<21>, NSLocalizedDescription=已取消} [-999]

**Comment by zhongwuzw** [comment]
@JKjiangnan Do you use `UITableView` or `UICollectionView`? because cell or `imageView` would be reused, so if we get a cell from reuse queue and set a new image url, we would cancel the download task of previous image, so these cancellation logs would be appear, do you faced any issue besides these annoying logs?

**Comment by dreampiggy** [comment]
He means when using http or `SDWebImageRefreshCached` in iOS 12, there will be frequtelly `NSURLErrorCancelled (-999)` error.

 But however, there are no any different in my test on iOS 12 simulator && real device.

@JKjiangnan If you means you will see some logs in the console output, it's the standard output for Apple's URLSesson framework, each time you call [NSURLSessonTask.cancel()](https://developer.apple.com/documentation/foundation/nsurlsessiontask/1411591-cancel) on it. Just ignore it. Because from Xcode 8, Apple 's own framework using [OSLog](https://developer.apple.com/documentation/os/oslog), they all output to the same console and save it into the log files.

**Comment by tdios** [comment]
Been using this library for weeks without issue and now that that iOS12 has been released, I am seeing the same issue as @JKjiangnan.  I see load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" for every call I make with this library.  Worked fine in iOS 11.  
I'm using this library in 2 different ways.  One, the sd_setImageWithURL call in the exact same way that your https://raw.githubusercontent.com/rs/SDWebImage/4.1.2/Docs/HowToUse.md describes.  Also using the loadImageWithURL call.  
Again both were working fine for weeks and now only the placeholder is displaying.

**Comment by JKjiangnan** [comment]
@zhongwuzw Thanks for your translation

**Comment by JKjiangnan** [comment]
@dreampiggy Yes, except for these logs, everything else can be used normally, but before iOS12, there would be no such logs.
And I will try your suggestion, thanks.
