### ISSUE TITLE
Using SDWebImage without use_frameworks

### ISSUE THREAD

**Issue by michaeleisel** [SDWebImage/SDWebImage#2547]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0+
 SDWebImage Version      | latest
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10

### Issue Description and Steps

In the readme it mentions that you have to use `use_frameworks!` in your Podfile if you add SDWebImage to a Swift project, why is that? Having that line means all of my libs get linked as dylibs, adding hundreds of ms to the startup time.

**Comment by dreampiggy** [comment]
This readme seems out of date. Currently, we're a pure Objective-C/C code framework, without any line of Swift code in framework itself. So you can use whether static linking or dynamic linking.

This readme maybe about the old day, before Xcode 9 (Swift 4) was released, because at that time, all Swift framework should be dynamic linking. And you have to use `use_framework!` in your Podfile if you are using any Swift framework. So maybe that readme is for those simple user. But actually, this description is not correct.

**Comment by dreampiggy** [comment]
Another issue, maybe about the using Swift code from a static Objective-C library. You should using the bridging headers. Because if you directlly import SDWebImage from the Swift side, CocoaPods generated xcconfig does not supports this and will trigger a compile issue.

See: https://stackoverflow.com/questions/31884507/how-to-use-objective-c-cocoapods-in-a-swift-project

**Comment by zhongwuzw** [comment]
@michaeleisel currently you can use `SD` as static library, just remove `use_framework!` and use `use_modular_headers!` instead:

```
use_modular_headers!
```

**Comment by michaeleisel** [comment]
Ok thanks. It would be great if the readme was updated with this info

**Comment by michaeleisel** [comment]
Ah I see there’s a PR

**Comment by bpoplauschi** [comment]
@michaeleisel just to throw another option on the table:
- using a simple hack you can `use_frameworks!` but link them statically instead of dynamically. See https://github.com/CocoaPods/CocoaPods/issues/7428#issuecomment-377864948
That way you can build your dependencies as frameworks, but avoid paying the app startup cost of loading a lot of dynamic modules.

**Comment by michaeleisel** [comment]
Nice, that’s an interesting way to do it. I’m in favor of any explanation in the readme that either discourages dynamic libraries or makes it clear that they impact startup time, as I see so many apps pay the price for dylib loading unnecessarily

**Comment by bpoplauschi** [comment]
We can add something to the readme, but I'm afraid most people will be confused with that level of detail. For most app creators that use only a handful of pods, using dynamic frameworks is not bad. App startup performance is still good, as Apple invested heavily in improving the loader (around iOS 9.3 if I remember correctly). The app I'm currently working on had more than 40 dynamic frameworks linked to it and still pre-main time was around 1 second for a cold start and better for warm starts. That is not ideal, but it's an acceptable number for a regular app.
I also think it's not this project's scope to go into the details of which install method to be preferred :) we try to support as many as possible and allow the users to choose. The dynamic vs static discussion is too big for us to handle, and there still isn't any silver bullet :)
But thanks for raising the issue, as it may help others by reading this conversation

**Comment by michaeleisel** [comment]
IMO one second is quite large but I understand
