### ISSUE TITLE
When will the 5th edition be released?

### ISSUE THREAD

**Issue by ChenXingBinInAnXi** [SDWebImage/SDWebImage#2638]
When will the 5th edition be released?

**Comment by dreampiggy** [comment]
The roadmap, there are another beta 5.0.0-beta6. Hopefully this release does not have any serious bug, so it will become the final beta releasee. From now on, there are no `Feature` to be added until the 5.0.0 official release.

The 5.0.0 release have already taken too long time to finish. Because our maintainer lack of free time to do this. But I hope people who are using this framework or people who are interested in open source can help for contribution.

**Comment by dreampiggy** [comment]
The 5.0.0-beta 6 is release. This is the final beta version of 5.0.0. And no more features will be added until the 5.0 release published.

**Comment by dreampiggy** [comment]
@ChenXingBinInAnXi Hi. SDWebImage 5.0.0 version, has already been released today. See the full changelog here: https://github.com/SDWebImage/SDWebImage/releases/tag/5.0.0

You can update your Podfile and have a try.

```
pod 'SDWebImage', '~> 5.0'
```
