### ISSUE TITLE
How to rename SD's source file from dot m to mm

### ISSUE THREAD

**Issue by Insofan** [SDWebImage/SDWebImage#2655]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios / macos / tvos / watchos
 Platform Version        | 1.7.0.beta.2
 SDWebImage Version      | 5.x
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1

### Issue Description and Steps
I wanna rename SD source file from dot m to mm,the project getting error 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SDMemoryCache", referenced from:
      objc-class-ref in SDImageCacheConfig.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
or 
`'Build input file cannot be found'`

**Comment by dreampiggy** [comment]
> I wanna rename SD source file from dot m to mm

I don't understand this use case.

Are you creating a modified version of SDWebImage ? If so, it's your responsibility to check for the compile issue or build issue. We can not provide help for the modified version for each one.

And, the `.mm` is used to build the file as Objective-C++, instead of Objective-C. Which have some limit on both Objective-C code and C++ code. Maybe you need to check the verbose log about it ?

**Comment by Insofan** [comment]
> > I wanna rename SD source file from dot m to mm
> 
> I don't understand this use case.
> 
> Are you creating a modified version of SDWebImage ? If so, it's your responsibility to check for the compile issue or build issue. We can not provide help for the modified version for each one.
> 
> And, the `.mm` is used to build the file as Objective-C++, instead of Objective-C. Which have some limit on both Objective-C code and C++ code. Maybe you need to check the verbose log about it ?

I wanna refactor the memory cache logic to LRU implementation with cpp, using map vector and deque or list struct.

**Comment by dreampiggy** [comment]
@Insofan Good first feature. Like some one's idea of #1912 .

Actually, there are already one LRU implementation, though it's not by default. See [SDWebImageYYPlugin](https://github.com/SDWebImage/SDWebImageYYPlugin).

This is a plugin, to use `YYCache` instead of `SDImageCache` for our cache system. The `YYCache` is combined by 3 components:

+ YYMemoryCache: A C implemented LRU cache using double-link node, See [YYMemoryCache.m](https://github.com/ibireme/YYCache/blob/master/YYCache/YYMemoryCache.m)
+ YYDiskCache: A disk cache based on the YYKVStorage, a wrapper to use both file and SQLite db.
+ YYKVStorage: A K-V storage based on SQLite blob storage.

I guess these is helpful for you

**Comment by dreampiggy** [comment]
Though I think the refactory can not get into the data of 5.0.0 official release. (The last version beta6, have already collected all feature in 5.0, until the 5.0.0 released, only bugfix, documentation or internal project change is accepted)

**Comment by Insofan** [comment]
> accepted
Actually I have read the YYCache and other cache libs. I haven't found a best solution on disk cache, all of them depended on NSFileManager exclude YYCache, but it based on sqlite, I don't think it's a good idea, if you have any disk cache idea plz tell me.After reading libs, on my opinion the best memory cache solution is using cpp stl. But YYCache's memory cache is good enough.Maybe I should implementation with it's skeleton.And I don't wanna modified the memory interface, just change the SDMemoryCache implementation. And it may takes a little time, recently I have several interviews.I if you have any suggestions leave message for me. Thx for ur and other's contributions to SD.

**Comment by dreampiggy** [comment]
@Insofan I can succesfully change `SDImageCache.m` into `SDImageCache.mm` and build Objective-C++ code. Are you sure you're using the correct steps to run SDWebImage framework or Demo ?

If you need to build framework only, do not need cocoapods. Open `SDWebImage.xcodeproj` and build.

If you need to build example, the example use the cocoapods. So

```bash
cd Examples
pod install
open ../SDWebImage.xcworkspace
```

If you need to run tests, do the same thing. So 

```bash
cd Tests
pod install
open ../SDWebImage.xcworkspace

**Comment by dreampiggy** [comment]
You need to update the podspec, to match the `.mm` files as well in source_files.

```ruby
core.source_files = 'SDWebImage/*.{h,m,mm}', 'WebImage/SDWebImage.h', 'SDWebImage/Private/*.{h,m}'
```

**Comment by dreampiggy** [comment]
<img src="https://user-images.githubusercontent.com/6919743/55226338-bb503280-524f-11e9-810e-fec3863d1016.png" width=300 height=300 />

**Comment by dreampiggy** [comment]
Actually...We're not really encourage Objective-C++ in SDWebImage. Because using C++ code wil increase the complexity of linkage issue, or API issue. C++ symbol should not expose to any Public API, because Swift can not using any C++ symbol and will ignore total files.

Instead, I suggest to use pure C to implements the same thing. And since our framework concentrate on only Apple platforms. You can using any C framework like Core Foundation, Accelerate for basic data structure or algorithm. But anyway, it's up to you.

When you finish your implementation, we can profile a benchmark to see the difference and decide whether it's suitable to merge.

**Comment by Insofan** [comment]
I'm coding the oc & c implementation using core foundation which based on yycache skeleton, perhaps  sunday it will done pre version. I will invite u to review code.

**Comment by Insofan** [comment]
> Actually...We're not really encourage Objective-C++ in SDWebImage. Because using C++ code wil increase the complexity of compile and linkage issue, or API issue. C++ symbol should not expose to any Public API, because Swift can not using any C++ symbol and will ignore total files.
> 
> Instead, I suggest to use pure C to implements the same thing. And since our framework concentrate on only Apple platforms. You can using any system C framework like Core Foundation, Accelerate for basic data structure or algorithm. But anyway, it's up to you.
> 
> When you finish your implementation, we can profile a benchmark to see the difference and decide whether it's suitable to merge.

I have finished a preview version. [SDMemoryCache.m](https://github.com/Insofan/SDWebImage/blob/cache/SDWebImage/SDMemoryCache.m). Plz review it. I confused with one issue. The original hash map memory cache logic is only on iOS/tv os platform, other platforms is based on NSCache, after refactor to LRU algorithm I think it adapted to all platforms, but I'm not sure  on macOS cause original comment says "macOS use virtual memory and do not clear cache when memory warning". 
And the pre vision refactor on adapter pattern, I don't wanna change the api interface, I only change one property in SDImageCacheConfig, if this logic approve maybe we should change more config and cache logic. If needed to promote efficiency the cache algorithm replace to LRU-K(2), I think it is better then now LRU(which k is 1) implementation, but actually LRU is also good enough.

**Comment by Insofan** [comment]
If this through, this mr into 5.0.1, 5.1.0 or other branch, I want to change more file and provide more option for memory cache strategy.

**Comment by dreampiggy** [comment]
@Insofan 5.0.0 is released. You can create a draft PR or PR, for your memory cache implementations. So that the contributors can have a review.

**Comment by dreampiggy** [comment]
Move the discussion and feature review for #2682
