### ISSUE TITLE
Does turning on GIF encoding and decoding affect the performance of displaying static images？

### ISSUE THREAD

**Issue by LL1992** [SDWebImage/SDWebImage#2656]
Use [[SDWebImageCodersManager sharedInstance] addCoder:[SDWebImageGIFCoder sharedCoder]] in App。UIImageView can show GIF. But it may reduce the performance .
My question : does it affect performance when UIImageview shows a static image?

Thank you！

**Comment by dreampiggy** [comment]
> does it affect performance when UIImageView shows a static image?
The answer is NO.

Actually, maybe this is the common question about the comment here. I can reply the detail.

### What means `reduce the performance`

If you using the GIF coder, on a normal UIImageView (Not our custom subclass or `FLAnimatedImageView`), only the animated image, create by using UIKit's API: [animatedImageWithImages:duration:](https://developer.apple.com/documentation/uikit/uiimage/1624149-animatedimagewithimages?language=objc) can rendering the animation.

However, this API, will retain all your supply UIImage frames into a internal array, and rendering using the Core Animation's `CAKeyframeAnimation`. Although it's a implementation detail, but keeping in mind: `ALL the UIImage frames is keeping in RAM during rendering`.

A UIImage, keeping the backing store of the Pixel Bitmap, which is just a pixels vector. Let assume one bitmap frame: 1000x1000 pixel resolution, 32bit color. This frame, will occupy the RAM size:

```
1000 * 1000 * 4(bytes per pixel) = 4000000 bytes ~= 4MB
```

So this is the problem. If you have a large size of GIF, which contains multiple frame to display, such as 100 frames. This animated image, will occupy 100MB in RAM. 

iOS/tvOS, unlike macOS, does not have virtual memory, and the hardware mostlly have limited RAM. So, if you rendering even 10 GIFs like this one, your RAM usage is up to 1GB and may cause a OOM to kill the app.

### FLAnimatedImage
In the earily day of 4.0, we bind another third-party framework [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage) to help for this. The `FLAnimatedImageView`, using another way to rendering the large GIF images. It's called the decoding the frame just in time.

Which means, if the above image (1000x1000, 100 frames) is begain to render, we do not keeping all frames into memory. Instead, we setup a timer, each time the next frame is needed to render, we decoding it just in time. And keeping a limited frame cache in memory.

So even for a huge GIF, the memory usage is under the control. Well, by costing the extra CPU to do decoding each time you need new frame to rendering. It's a trade-off between CPU && RAM. Learn more on FLAnimatedImage's own readme.

### What will change if I enable GIF coder

**Note: All I talk about here, it's about SDWebImage 4.0 behavior. Not 5.0**

Sadly, due to the old architecture of SDWebImage 4.0, we have no way for decoder, to distinguish whether the image request, is come from a `UIImageView`, who need a `UIAnimatedImage`; Or the image request is come from a `FLAnimatedImageView`, who need a `FLAnimatedImage` (Sadly again, it's not a UIImage subclass, which means it's not conforms to our block args).

By default, when you don't add GIF coder to coders manager, we only decode all GIF images, as static with the 1st poster image. If the target imageView is FLAnimatedImageView, we will re-decode the original data into the `FLAnimatedImage`, else, just sending it like normal JPEG image.

If you add GIF coder to coders manager, we will decode GIF images follow it's frames count. Always produce the `UIIAnimatedImage` contains all frames in RAM. But actually, if this time, the target imageView is FLAnimatedImageView, they don't need this `UIAnimatedImage` and drop it. Then still re-decode the original data into the `FLAnimatedImage`... 😓 

So this is the meaning `Reduce the performance when using FLAnimatedImage`. It still works, but not friendly for RAM usage.

## What 5.0 changed for this ?
In 5.0, we introduce a new `context option` arg, to pass the enough information to decoder. Now decoder can decide to use the correct image class for different image view class. This solve the problem above.

And, due to the suck of FLAnimatedImage, we create our own solution for Animated Image Rendering. See more here: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50

You can read the wiki if you want to know the problems and the soluition detail. But here, I just take a summary: The 5.0 improvde the Animated Image rendering solution, and you can always safelly to add GIF coder to coders manager. (It's also the default behavior). Works for both UIKit's `UIImageView` as well as the custom `SDAnimatedImageView`, with no harm for each others.

**Comment by LL1992** [comment]
@dreampiggy Thank you very much. I'll study it carefully

**Comment by dreampiggy** [comment]
@LL1992 SDWebImage 5.0.0 is already released today. You can have a try and provide feedback. See (Change log)[https://github.com/SDWebImage/SDWebImage/releases/tag/5.0.0]
