### ISSUE TITLE
5.0.0版本如何禁止gif播放

### ISSUE THREAD

**Issue by QuintGao** [SDWebImage/SDWebImage#2679]
SDWebImage5.0.0版本使用UIImageView加载gif网络图片会自动播放gif，该如何禁止其自动播放，我想在只使用SDAnimatedImageView的时候才去播放gif图片。

**Comment by dreampiggy** [comment]
@QuintGao From the wiki page:

Current you can using `.decodeFirstFrameImage` to avoid a animated image decoding (UIImageView with UIAnimatedImage).

Do you means, you want a global options to config this behavior ? Instead of config each of imaeg request?

**Comment by QuintGao** [comment]
Thank you very much. It would be better if this problem could be solved by global configuration. Now I know how to deal with it.

**Comment by dreampiggy** [comment]
@QuintGao You can create a feature request.

I found people need **Both global configuration and individual configuration** use cases.

For example, when using `avoidDecodImage`, some user want only specify images to force decode in background, others are not. Like #1927.

But some other user, want to global disable this feature. Like #2672.

So, maybe it's better to have a following property, in the manager level and provide a default options. If your individual image request does not apply any options, use the default one ?

```objective-c
@interface SDWebImageManager

@property (assign) SDWebImageOptions defaultImageOptions;
@property (nonatomic, strong) SDWebImageContext *defaultImageContext;

@end 
```

If we support only `apply the default options when I don't provide any !`, it's easy.

But there are also one problem...How to solve `but...for some specify options, I want to delete the config as well`. Because `SDWebImageOptions` is a enum using masks. You can using enum to represent both of two sematic (Add one mask, and remove one mask). So this is why at the 5.0 development time, we don't simply add this feature.

**Comment by hao-feng** [comment]
You can remove the default SDImageGIFCoder, and add your own GIFCoder which returns the SDAnimatedImage instead of _UIAnimatedImage

**Comment by kingnight** [comment]
> 



> You can remove the default SDImageGIFCoder, and add your own GIFCoder which returns the SDAnimatedImage instead of _UIAnimatedImage

@hao-feng @QuintGao  Do you have a specific demo code? Or the latest best solution?
