### ISSUE TITLE
如何保证一个地址只下载一次

### ISSUE THREAD

**Issue by YellBinn** [SDWebImage/SDWebImage#2716]
SD Ver:3.8.2
Xcode:10.2.1
由于需要全局支持gif 所以使用了3.8.2版本
并发请求时，发现部分图片重复请求，地址是一样的
不知道源码是如何保证一个地址只下载一次？请告知

**Comment by dreampiggy** [comment]
> 由于需要全局支持gif 所以使用了3.8.2版本
You can enable this, by adding the `SDWebImageGIFCoder` into coders manager during setup as well. By default, the 4.x does not add the GIF coder. This does not need 3.8 version. See: [Wiki-gif-coder](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#gif-coder)

> 并发请求时，发现部分图片重复请求，地址是一样的
SDWebImage use the `SDWebImageDownloader`, which will firstly search all download operation with the same URL, and then bind the progressBlock and completionBlock into the target operation. If you request the same URL twice, it will bind the both two progressBlock and completionBlock into the same operation, which avoid duplicated operation.

If you see the same URL request twice, it may because you use the different `SDWebImageDownloader` instance, such as your own prefetcher or manual created one. And it use `NSURL isEqual:` to compare whether the URL is same, if the URL query is not the same, it will trigger another download. You can have a check yourself.

**Comment by YellBinn** [comment]
好的 我已经修改到这边的代码了
但是3.8.2的SDWebImageDownloader 不包含 URLOperations 用于区分URL
我从4.4.6中复制出部分需要的代码
感谢您的回复

**Comment by YellBinn** [comment]
你好 我发现在极端情况下 还是会请求两次
在SDWebImageDownloader - downloadImageWithURL中的判断
if (!operation || operation.isFinished || operation.isCancelled) 
如果获取到的operation是isFinished 将会再次发送请求

**Comment by dreampiggy** [comment]
`isFinished` means, this download operation is already marked as finished, because the URLSession callbacked, or the operation is canncelled. So we will never use this type of operation.

It's a designed behavior. If you use this finished operation, your NSOperationQueue will have a wrong behavior because we use the `completionHandler` property to sync the queue to downloader.

Learn more in https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationObjects/OperationObjects.html

**Comment by YellBinn** [comment]
是的 completionHandler会移除
但是我又发现一个问题，当completionHandler回调时会保存图片，但是在这时发起同一个图片请求（几十毫秒内），queryDiskCacheForKey会查不到图片，并且operation被移除了，这时也是会重新请求。

**Comment by dreampiggy** [comment]
The `save image data to disk` process after download, is now asynchronously. Which means, if you write some code like this, you're not gurantee to query the disk cache

```objectivec
[imageView sd_setImageWithURL:url completed:^{
    NSData *tempData = [SDImageCache.sharedImageCache diskImageDataForKey:key]; // This may become nil
}]
```

However, previouslly there are some user who want a extra option to control this behavior. Which means, only callback your completionBlock after the `save image data to disk finished`. If you need this, you can fire a feature request, which may be achieved later in 5.1.0 or higher.

**Comment by YellBinn** [comment]
感谢 这个思路不错
我现在的做法是completionHandler时没有移除operation 然后在operation加了一个image属性
当SDWebImageManager Cache到缓存时 才移除operation
