### ISSUE TITLE
encoding WebP for upload

### ISSUE THREAD

**Issue by mmdock** [SDWebImage/SDWebImage#2718]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found decoding issues, but not encoding

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.2
 SDWebImage Version      | 4.4.6
 Integration Method      | cocoapods
 Xcode Version           | Version 10.2.1 (10E1001)
 Repro rate                 | 100%
 Repro with our demo prj | Haven't tried
 Demo project link       | N/A

### Issue Description and Steps
Trying to encode UIImage user selected via camera roll to be WebP before uploading to my api.

With the following UIImage extension:
```
    func webPData() -> Data? {
        return SDWebImageWebPCoder.shared().encodedData(with: self, format: .webP)
    }
```

The time to receive that data is (Two different attempts):
Time elapsed for encodedData - WebP: 29.979711055755615 s.
@ 2 126 106 bytes for the image.

When doing something similar with jpg for the same image:

```
    func jpgData() -> Data? {
        return self.jpegData(compressionQuality: 1.0)
    }

```
Time elapsed for jpg, compression quality 1.0: 0.21848011016845703 s.
@ 6 385 345 bytes

This makes it incredibly difficult for me to implement being able to upload images to my api as WebP, since it has a 20-30 s lag depending on the image chosen.  

If there is a way to improve this performance, please let me know.

**Comment by dreampiggy** [comment]
JPEG encoding is Hardware Accelerated, which does not taken on your iPhone's CPU or run any ARM instruction, it's taken on the special SoC, maybe on the GPU. It's controleed by Apple's Image/IO framework and AppleJPEG implementation. Which is really fast and battery-friendly.

But WebP encoding, since Apple does not support WebP, it's taken by Google's [libwebp](https://developers.google.com/speed/webp/docs/api). It's a Software encoding, and running code on CPU, compared to slower than the Hardware encoding.

You can try to change some specify encoding options, to increase the encoding speed. For example, do not using the default `1.0` compression quality. WebP encoding on 1.0 quality, which spend more time for this. Using lossy encoding can increase the speed.

**Comment by dreampiggy** [comment]
And, you can try to upgrade to use the latest libwebp codec, to see if there are any performance difference. And remember, DO NOT RUN BENCHMARK ON SIMULATOR. You need to test the performance on Real Device. Because libwebp using some assembly code which may behave different on x86_64(SSE) and ARM(NEON)

**Comment by mmdock** [comment]
@dreampiggy Thanks for the feed back. Couple of questions: 

RE: "For example, do not using the default 1.0 compression quality. WebP encoding on 1.0 quality, which spend more time for this. Using lossy encoding can increase the speed." I am unclear on how to adjust the compression quality for WebP using SDWebImage.  I do not see support for that in the 4.4.6 release.

RE: "you can try to upgrade to use the latest libwebp codec (current is v1.0.2)" - That is something I am looking forward to trying.  Unfortunately, I am unable to right now as I use Braze/Appboy which is dependent on `SDWebImage/GIF, ~> 4.x.x`.  

RE: "You need to test the performance on real iOS device" - All benchmarks I gave was on a real device.

**Comment by mmdock** [comment]
Also, RE: "It's a Software encoding, and running code on CPU, compared to be slower than the Hardware encoding." -> Kinda crazy that there it is 137x slower to encode as webp than it is for JPEG

**Comment by dreampiggy** [comment]
@mmdock 

> Unfortunately, I am unable to right now as I use Braze/Appboy which is dependent on SDWebImage/GIF, ~> 4.x.x.

Emm. Does this dependency cause anything issue to block you upgrade to libwebp 1.0.2 ?

SDWebImage 4.4.6, have the following dependency for webp, See: [SDWebImage-v4.4.6.podspec](https://github.com/SDWebImage/SDWebImage/blob/4.4.6/SDWebImage.podspec#L62)

```ruby
webp.dependency 'libwebp', '>= 0.5'
```

Which means, you just need to run `pod update`, or add the correct version in your Podfile.

```
pod 'libwebp', '1.0.2'
```

**Comment by mmdock** [comment]
@dreampiggy I just assumed that pod 'SDWebImage/WebP', '~> 4.4.6'

**Comment by dreampiggy** [comment]
I run a local benchmark, on iPhone X device (iOS 12.2) with Release Configuration, seems the WebP encoding speed is 10x slower compared JPEG and WebP. With the compression quality 0.75. The test code is here: [ModernImageFormatBenchmark](https://github.com/dreampiggy/ModernImageFormatBenchmark)

```
<Decode> [PNG]: Time: 0.41 ms, RAM: 0.000 MB
<Decode> [JPEG]: Time: 8.09 ms, RAM: 0.000 MB
<Decode> [HEIC]: Time: 2.39 ms, RAM: 0.062 MB
<Decode> [HEIF]: Time: 35.01 ms, RAM: 0.016 MB
<Decode> [WebP]: Time: 4.08 ms, RAM: 1.000 MB
<Decode> [BPG]: Time: 12.11 ms, RAM: 0.750 MB
<Decode> [FLIF]: Time: 90.47 ms, RAM: 1.000 MB
<Decode> [AVIF]: Time: 42.72 ms, RAM: 1.156 MB
<Encode> [PNG]: Time: 26.89 ms, RAM: 0.016 MB
<Encode> [JPEG]: Time: 3.42 ms, RAM: 0.016 MB
<Encode> [HEIC]: Time: 44.44 ms, RAM: 0.594 MB
<Encode> [HEIF]: Time: 558.91 ms, RAM: 5.797 MB
<Encode> [WebP]: Time: 34.22 ms, RAM: 0.031 MB
<Encode> [BPG]: Time: 918.36 ms, RAM: 0.016 MB
```

Currently, I did not find anything better to improve the performance. The libwebp codec options for performance we've already used. Such as `use_threads` for multiple thread encoding.

**Comment by dreampiggy** [comment]
I'll continue to investigate the better performance enhancement solution for all image encoding/decoding part. If you find something related, or have some expert knowledge about Image Processing, feel free to contact.

**Comment by dreampiggy** [comment]
> I am unclear on how to adjust the compression quality for WebP using SDWebImage. I do not see support for that in the 4.4.6 release.

And, you're right. SDWebImage 4.x, does not support extra options for encoder/decoder , because of the old API design and architecture. There are no good way to support it.

This is also the reason why we create 5.0 version and break the API. See [5.0 changelog](https://github.com/SDWebImage/SDWebImage/releases/tag/5.0.0)
