### ISSUE TITLE
Feature Request - About GIF

### ISSUE THREAD

**Issue by Deeer** [SDWebImage/SDWebImage#2724]
### New Issue Checklist

* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios |
 Platform Version        | 12.0 |
 SDWebImage Version      |  5.0.0 |
 Integration Method      | cocoapods |
 Xcode Version           | Xcode 10 |
 Repro rate              | xxx |
 Repro with our demo prj |  xxx |
 Demo project link       | xxx |

### Issue Description and Steps

- How can I get the duration of one loop for a gif image loaded from network ? or will it provide a property to get the value easily ？
- How can I set the loop count for a gif  loaded from network ? I have try to set loop count
using `setSd_imageLoopCount` in the completion block but failed.

**Comment by dreampiggy** [comment]
> First, which type of Animated Image ?

SDWebImage 5.0, support two different kind of Animated Image. One is UIAnimatedImage/NSImage, which is the system type of image class, compatible for `UIImageView/UIButton/Today Extension/WatchKit`.

Another is the custom subclass of `SDAnimatedImage` class. Can play animation with the help of `SDAnimatedImageView`.

> get the duration of one loop

+ For `UIAnimatedImage`, you can not directlly get the frame duration, because of Apple's SDK limit, we repeated special frame for several times, so the `images` count is not frame count. However, you can try to use the [SDImageCoderHelper.framesFromAnimatedImage](https://sdwebimage.github.io/Classes/SDImageCoderHelper.html#/c:objc(cs)SDImageCoderHelper(cm)framesFromAnimatedImage:) to revert this patch and get the original frames. This apply the same of `NSImage`.

+ For `SDAnimatedImage`, you can call the protocol method [animatedImageDurationAtIndex:](https://sdwebimage.github.io/Protocols/SDAnimatedImageProvider.html#/c:objc(pl)SDAnimatedImageProvider(im)animatedImageDurationAtIndex:). Exactly what you need.

> set the loop count

The loop count, is the metadata of a compression image data itself, just like pixels, like EXIF orientation. You can not modify it, until you do a `re-encoding` to produce another image. You should understand this.
However, you can control the imageView render, to use your custom loop count. This what you need.

+ For `UIAnimatedImage` and `UIImageView`, you can use [UIImageView.animationRepeatCount](https://developer.apple.com/documentation/uikit/uiimageview/1621070-animationrepeatcount) to control the loop count. It's a read-write property.

+ For `SDAnimatedImage` and `SDAnimatedImageView`, you can use `SDAnimatedImageView.animationRepeatCount` with the [SDAnimatedImageView.shouldCustomLoopCount](https://sdwebimage.github.io/Classes/SDAnimatedImageView.html#/c:objc(cs)SDAnimatedImageView(py)shouldCustomLoopCount) set to YES. (NO will use the image meta loop count instead). See the documentation detail about it.

See more related wiki: [Animated Image](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50)

**Comment by Deeer** [comment]
I tried UIAnimatedImage and UIImageView case , the `UIImageView.animationRepeatCount ` not working for controlling loop count.

however when I turn to `SDAnimatedImage`,it dose work.
thanks :]

**Comment by dreampiggy** [comment]
@Deeer Maybe you don't use the Apple's SDK correctlly. And I'm agree with you that this is a trap and their documentation does not point this out. See [animationRepeatCount](https://developer.apple.com/documentation/uikit/uiimageview/1621070-animationrepeatcount?language=objc), there are interesting `See also` part.

If you want to control the `UIAnimatedImage` loop count, on `UIImageView`, you should not do like this:

```objective-c
UIImage *image; // Actually, a `UIAnimatedImage` instance created from `UIImage animatedImageWithImages:duration:
UIImageView *imageView;
imageView.image = image;
imageView.animationRepeatCount = 2; // loop 2
// However, this does not works, and still loop infinitely :)
```

Instead, you should do like this:

```objective-c
UIImage *image; // Actually, a `UIAnimatedImage` instance created from `UIImage animatedImageWithImages:duration:
UIImageView *imageView;

// Let's start the correct way
imageView.animationImages = image.images;
imageView.animationDuration = image.duration;
imageView.animationRepeatCount = 2;
[imageView startAnimating];

// using the above code to work with limit  loop count.
```
