### ISSUE TITLE
How to cacheMemoryOnly in v 5?

### ISSUE THREAD

**Issue by phoney** [SDWebImage/SDWebImage#2729]
cacheMemoryOnly was removed in v 5. I can't figure out how to get the same functionality in swift. I want to only have the inMemory cache used. No images should be written to the disk. (for HIPAA reasons).

How do I do this?

I looked in the 5.0 migration guide and advanced usage page but didn't find a clear answer.

**Comment by dreampiggy** [comment]
Dunplicated for #2698

```objective-c
[imageView sd_setImageWithURL:url placeholderImage:nil options:0 context:@{SDWebImageContextStoreCacheType : @(SDImageCacheTypeMemory)}];
```

Maybe I need to update the Wiki specify for this.

**Comment by dreampiggy** [comment]
Updated wiki about the 5.0 migration guide. It points out the replacement for the changing on `SDWebImageOptions`. See [here](https://github.com/SDWebImage/SDWebImage/wiki/5.0-Migration-guide#sdwebimageoptions)

**Comment by phoney** [comment]
Thanks for the answer. 

I wasn't able to find it because cacheMemoryOnly is the swift name. I think I still wouldn't find it in the 5.0 migration guide.

**Comment by dreampiggy** [comment]
@phoney Just translate the Objective-C to Swift...It's not hard.


```swift
imageView.sd_setImage(with: url, placeholderImage: nil, options: [], context: [.storeCacheType : SDImageCacheType.memory])
```

**Comment by phoney** [comment]
That wasn't my point. I couldn't find the documentation on this because I was looking for cacheMemoryOnly. It's not in your documentation because it's swift and because you removed it.

**Comment by dreampiggy** [comment]
Because Objective-C API is automatically exported to Swift by clang. For people who use Objective-C exported API for Swift, they can easy to find the correspond API after changes (Since we does not do something like re-write the Swift API from scratch.).

The only difference is the syntax, but not the meanning or name. For example, the Objective-C API `SDWebImageProgressiveDownload` => `SDWebImageProgressiveLoad`, the Swift API changes is `.progressiveDownload` => `progressiveLoad`.

The Swift part of migration guide, point out the little hard because we follows Apple's documentation for [Imported C and Objective-C APIs](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis). Which provide a better representation for Swift, and may change the syntax, like the `NS_TYPED_ENUM`, which will generate `struct` instead of original `String`. So we explicitly point this out.
