### ISSUE TITLE
Pod Update Failure 

### ISSUE THREAD

**Issue by Hamna21** [SDWebImage/SDWebImage#2754]
Hello,

I am using Xcode 10.1 and have set minimum deployment target to 11.4. 
I am trying to update pod to ~5.0 but getting error regarding changing minimum deployment target.

Can you please specify the min. deployment target?

**Comment by dreampiggy** [comment]
Could you please fill the issue template ? Or we can not get the environment to find the issue.

For your description, you're using SDWebImage as integration project on iOS ?

If you want to know how to write Podfile, just check [cocoapods-podfile](https://guides.cocoapods.org/using/the-podfile.html)

```
platform :ios, '11.4'

target 'MyApp' do
  use_frameworks!
  pod 'SDWebImage', '~> 5.0'
end
```

**Comment by Hamna21** [comment]
Platform Name | iOS
Platform Version | 12.0
SDWebImage Version | 5.0.0
Integration Method | cocoapods
Xcode Version | Xcode 10.1
Repro rate | xxx
Repro with our demo prj | xxx
Demo project link | xxx

I know how to write a Podfile. My question is regarding the minimum deployment target. I have set it to 11.4 but I am still getting the error message.
I am not using SDWebimage pod directly. It's a dependency for FirebaseUI and CleverTap.

**Comment by dreampiggy** [comment]
> I have set it to 11.4 but I am still getting the error message.

For Pod dependency, they follow the rule that downstream (which is depenedent by other Pod) min deployment target version, should be equal or lower than the upstream Pod.

Which means, if one Pod you're using, use something like this:

```
// A.podspec
spec.ios.deployment_target = '8.0'
spec.dependency 'SDWebImage'
``` 

Then you try to use A and `SDWebImage 5.0`, you will find the dependency resolve failed. Because SDWebImage 5.0's min deployment target version is iOS 8.0+.

You'd better provide your Application Podfile, so I can simualate the case. But you can also analysis yourself. If you face this issue, ask the `A` Pod author to upgrade their dependency.

**Comment by Hamna21** [comment]
Thank for the help! I resolved it!

**Comment by dreampiggy** [comment]
@Hamna21 OK...Could you mind please tell the detail reason for this ? To help for other people who may face the same problem.

**Comment by Hamna21** [comment]
@dreampiggy Sorry for late reply!

I went through CleverTap Docs and updated that pod to latest version prior to updating SDWebImage. That solved the issue.
