### ISSUE TITLE
SDAnimatedImage.animatedImageData documentation doesn't reflect behavior

### ISSUE THREAD

**Issue by krze** [SDWebImage/SDWebImage#2770]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 12
 SDWebImage Version      | 5.0.6
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2
 Repro rate              | 100%
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps
While upgrading to 5.0.6 from 4.x, I was relying on `UIImage sd_isAnimated` to check if an image was animated. I noticed that fails to report a proper value for animated webp's, because it's checking `self.images != nil`. I saw that [SDAnimatedImage.animagedImageData's documentation says the following:](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDAnimatedImage.h#L89)
```
/**
 Current animated image data, you can use this instead of CGImage to create another instance.
 If the current image is not animated image, this value is nil.
 */
```
I wrote a little extension in our app to use this property's nil/not nil value to check to see if the image was animated. However, I discovered that with single-frame, non-animated PNGs, this property was not nil, since it fell through to the PNG coder's imageData field, which was not nil.

I found that the most effective way to tell if an image was animated was to check the `animatedImageFrameCount` instead. Since our app supports .gif, .webp, and .png, it was the most reliable indicator.

**Comment by dreampiggy** [comment]
> If the current image is not animated image, this value is nil.

Seems the implementation behavior is `If this image is created with the API `initWithData:scale:`, `initWithContentsOfFile:` or `initWithAnimatedCoder:scale:`, this value is non-nil`

I'll provide a update for this documentation.

> I was relying on UIImage sd_isAnimated to check if an image was animated

Actually, previouslly I want to add the check code handle for this as well, which means:

```objective-c
- (BOOL)sd_isAnimated {
    if (image.images.count > 0) {return YES}
    if ([image responseToSelector:@selector(animatedImageFrameCount)] && image.animatedImageFrameCount > 0) { return YES };
    return NO;
}
```

But I guess this may cause some inner break for caller. Because the `SDAnimatedImage` and `UIImage` is different in some behavior. For example, if you want to grab the data buffer (called encoding) for image, for `SDAnimatedImage`, you don't need to re-encode, just grab the `animatedImageData` property). So seperate these two cases can make your code more clear and performent on each cases.

If you think, we SDWebImage should handle this `SDAnimatedImage` case in `sd_isAnimated` method, please provide your detail use case and we may change this in the future.

**Comment by krze** [comment]
>If this image is created with the API initWithData:scale:, initWithContentsOfFile: or initWithAnimatedCoder:scale:, this value is non-nil

That explains the odd behavior. It was non-nil in unit tests because we were using `initWithContentOfFile`. Thank you

>If you think, we SDWebImage should handle this SDAnimatedImage case in sd_isAnimated method, please provide your detail use case and we may change this in the future.

In our use case, we had already implemented an image manipulation operation before 5.x, where we blur or round corners on images. We choose to prevent this operation from occurring on animated images because it would take too long to apply the manipulation to every frame (plus use a lot of memory). We were using `sd_isAnimated` to check for an animated image because our backend will return both still or animated `WebP`'s or `GIF`'s, so checking the format would be inefficient. Checking for the presence of `> 1` frames was the most efficient operation.

**Comment by dreampiggy** [comment]
@krze Your use case is the same as our check for `SDImageTransformer` and `SDWebImageTransformAnimatedImage` option. Like [SDWebImageManager.m](https://github.com/SDWebImage/SDWebImage/blob/5.0.6/SDWebImage/SDWebImageManager.m#L300)

> because it would take too long to apply the manipulation to every frame

Depends on transform usage. If you want to apply transform even on animated image's each frame, seems we need handle this case. And you still have to concentrate about the `@protocol SDAnimatedImage`. Because you have to use `animatedImageAtIndex:` API, instead of that `images` property.

The `UIImage.animatedImageWithFrames:` and `SDAnimatedImage.imageWithData:` is extreme different design and implementation, the later one is more like `NSImage.imageWithData:`. Which does not hold hole frame buffer. It only provide by use.

So I'm worried if we put them together in a method called `isAnimatedImage`, will cause some hard to find error from the client side code. I think the client side should always handle both `isAnimatedImage && isAnimatedImageProtocol` two cases separately...

I'll find some feedback about this, to detect whether we should have a change. The documentation part is OK to update.

**Comment by dreampiggy** [comment]
If we change the `sd_isAnimatedImage` to handle the `@procool SDAnimatedImage` case, should we also update other checks as well ?

For example: 

+ sd_imageFormat
This should use `animatedImageFormat` or `animatedImageData` with `NSData.sd_imageFormatForImageData`

+ sd_imageLoopCount
This should use `animatedImageLoopCount` API instead for `@protocol SDAnimatedImage`

**Comment by krze** [comment]
We've found our workaround to be a low-effort fix. I think the biggest issue was the incorrect documentation and unexpected behavior. I don't have a particularly strong case for combining these checks under one umbrella
