### ISSUE TITLE
The CPU usage occupied by WebP is too high.

### ISSUE THREAD

**Issue by zhipengbird** [SDWebImage/SDWebImage#2795]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  12.0 
 SDWebImage Version      | 5.0.6
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 11 / Xcode 10
 Repro rate              | all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project? YES

### Issue Description and Steps
Create a new Clear project.  Use  SDAnimatedImageView to  load webp images. The CPU usage explodes to 100%, once the Animation stoped , CPU usage dropped to  0%. Different webp resource animations are played for a long time, and CPU usage is always maintained at about 100 per cent. Cell phone fever is also very serious.  How do I do that to reduce CPU usage？ Please help me!  Thank you !

These are some of the materials I use.
[source.zip](https://github.com/SDWebImage/SDWebImage/files/3425752/source.zip)

**Comment by dreampiggy** [comment]
Try to change the `maxBufferSize`. This is the balance between CPU && memory. You can just set this value to NSUIntergerMax to give 0 CPU usage, but this may cause much more memory.

**Comment by dreampiggy** [comment]
And the performance test is based on what device ? Provide you detail performance profile environment (Hardware model, iOS version, etc)

**Comment by zhipengbird** [comment]
After I set maxBufferSize to NSUIntergerMax, I re-compared performance on different models, and CPU usage is still very high. The following table shows my test data records (the peak when CPU was used). Are there any other ways to reduce CPU usage?
Comparison of webp performance data 

webp   Source | iPhone5(10.3.3) | iphone 6(10.3.3) | iphone 6(12.3) | iphone 6p(12.2) | iPhone 7(11.3) | iPhone 8(13.0)
-- | -- | -- | -- | -- | -- | --
big.webp(4.6M) | 98% | 105% | 97% | 96% | 76% | 75%
small.webp(1.5M) | 103% | 77% | 75% | 64% | 41% | 42%
middle.webp(880K) | 95% | 60% | 50% | 52% | 34% | 39%

**Comment by dreampiggy** [comment]
> After I set maxBufferSize to NSUIntergerMax

Is this bug ? Change the buffer size to max means we behave like `UIImageView` and `UIAnimatedImage`. All the frame is always keep in RAM, no any CPU usage for decoding when rendering. It should only consume GPU for rendering on layer.

Any reproducable demo ? The SDWebImage demo can not get your test result for this.

And, you should attach your WebP coder plugin version , to see whether it's a bug in [SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder), but not SDAnimatedImage

**Comment by zhipengbird** [comment]
This is my demo address, you can download it. After running, select webp, to see the effect. CPU utilization is really high. If you have any good suggestions, you can reply to me.
[Demo](https://github.com/zhipengbird/giftPlayer.git)

**Comment by dreampiggy** [comment]
@zhipengbird I review your demo code again. The performance drop is because of your usage code.

`SDAnimatedImageView`, keep the frame buffer cache in `Per ImageView Level`. Which means it does not shared or cached in a global cache system. It's bind into a imageView internal storage.
And it only cache the `Current Played Image`, when a new `setImage:` was trigged, your previous frame buffer will be purged.

Your demo code, use the following code, to release the imageView after animation is stopeed.

![image](https://user-images.githubusercontent.com/6919743/62005086-73d7a580-b160-11e9-9c0b-751a0e450457.png)


If you reuse a imageView to a new image. All of previous individual frame will been purged. So if you play WebP Animation one by one using the same imageView. Actually, you just decode frames, render them, release them one by one. No any global shared cache is used.

This is a designed behavior for most caces. Because if you cache the image frame between different animated image, the memory occupy is huge. (Assume you play 10 different URLs on one imageView).

For your use case, I think you can try some of below solution

1. Use `PreloadAllFrames` options, this will preload all the individual frame buffers into the `SDAnimatedImage` instance and cached by memory cache. So that you don't need to re-decoding. But this consume much more memory. Take a balance between this or limit the memory cache max size (SDImageCacheConfig.maxMemoryCost)
2. Write your custom animation player, which share the frame cache between different animated images. But I think it's much harder than 1 option
3. WebP software decoding is dramatically slower than APNG/GIF decoding (hardware on iOS). If you care CPU usage, you can try to transcode the WebP images in client side, into the `APNG` format or `GIF` (if image has no alpha channel, this is the best opinion)
