### ISSUE TITLE
[USAGE] Custom indicator within UICollectionView reuse issue

### ISSUE THREAD

**Issue by CraftizLtd** [SDWebImage/SDWebImage#2800]
* [ ✅] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ✅] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ✅] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | iOS 12.4
 SDWebImage Version      | 5.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | Sometimes 30$
 Repro with our demo prj | Probably yes

### Issue Description and Steps

Hey there,
Just wanted to start by saying thank you for providing us this priceless lib!

Within our project, we are using a custom "shimmer" while the `UICollectionViewCell` loads an image (`sd_setImage`):

![Simulator Screen Shot - iPhone X - 2019-08-01 at 09 53 59](https://user-images.githubusercontent.com/41643229/62264599-62351d00-b442-11e9-9c42-466720524945.png)

The "shimmer" is a `subview` of the `UICollectionViewCell` with an animated `CAGradientLayer`. 

The issue is that sometimes, altho the image hasn't been loaded yet, `sd_setImage` completion block gets called before the image is actually appearing, so the shimmer stops but there is no actual image applied (tho seems that after a few seconds it magically appears).

This is how we implemented `cellForItemAt`:

```
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {

let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "StoryCell", for: indexPath) as! StoryCollectionViewCell
let url = <URL>
cell.previewImage?.sd_setImage(with: url, completed: { [weak cell] (image, error, cacheType, url) in
        if image != nil {
                DispatchQueue.main.async { // stop shimmer
                    cell?.shimmerView.stopShimmering()
               } 
            }
        })
return cell
}
```

Where `stopShimmering()` is:

```
func stopShimmering() {
        gradient.opacity = 0
        gradient.removeAllAnimations()
        layer.mask = nil
        backgroundColor = .red // just for testing
}
```

When the `stopShimmering()` method gets called the background changes to red color, just as a dummy indicator.  Demonstration of the issue below. As you can see it's been "loaded" (shimmer stopped) but there's no image.

![IMG_7840](https://user-images.githubusercontent.com/41643229/62264938-ed62e280-b443-11e9-922d-7b1fb3794e77.PNG)

Is something with the implementation wrong? Would love to know, shipping this to production soon :)

Thank you for this amazing lib!

**Comment by dreampiggy** [comment]
1.

```
DispatchQueue.main.async
```

This is unnecessary, since we always call your completion block on main queue. This code will submit your UI render into next Runloop, and may cause issue (If at the same time, another code was modify the `imageView.image` in sync, which means current Runloop, you'll see a flash).

2. Some `SDWebImageOptions` will dramatically impact the loading behavior for this `sd_setImage(with:)` logic, such as `avoidAutoSetImage`, `delayPlaceholder`. So you'd better check your implementation to see whether there are some special options effect this.

3. The `SDWebImageTransition` can also make the `setImage` logic become async, which means `we call your completion block before the imageView.image is set, only the image instance is valid, don't assume anything about order`.

4. You can try to move your custom `shimmerView` into a `SDWebImageIndicator` protocol, which may behave more correct since you don't need to manual control the `start` and `stop` status, and we provide the timming to call your protocol method implementation. See more here: [Use View Indicator ](https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#use-view-indicator-50)

**Comment by CraftizLtd** [comment]
Hey @dreampiggy, thank you for replying.

1. I removed the extra `DispatchQueue.main.async` code.
2. There are not options at all actually, using the default `SDWebImage` implementation, so I guess it's not the source. 
To avoid re-deleting the app every time, all I added in `AppDelegate` is this line:
```
SDImageCache.shared.clearMemory()
SDImageCache.shared.clearDisk()
```
But I don't think it's affecting anything.

3. For test purposes, I removed the fade but seems that it's still not working properly with my current implementation. 
Two things come to my mind:

- I'm using `Network Link Conditioner` on my device to simulate below-average internet speed (3G), maybe something with slow internet calls the completion block before hands?

- Maybe the completion block getting called but it's still decoding the image? Or it's not reasonable?

4. I tried implementing `SDWebImageIndicator` like this:
```
class ShimmerIndicator: UIView, SDWebImageIndicator {
    var indicatorView: UIView = FAShimmerView()
    
    func startAnimatingIndicator() {
        (indicatorView as? FAShimmerView)?.startShimmer()
    }
    
    func stopAnimatingIndicator() {
        (indicatorView as? FAShimmerView)?.stopShimmering()

    }

}

```

And then in `CellForItem` simply doing this:
```
cell.previewImage.sd_imageIndicator = ShimmerIndicator()
cell.previewImage?.sd_setImage(with: URL(string: urlString), completed: nil)
```
So it'll handle everything by himself but seems like when it's fetching the image it's calling the 'Stop' function but doesn't set the image (seeing only red background as before).
Wrong implementation?

**Comment by dreampiggy** [comment]
> maybe something with slow internet calls the completion block before hands?
This should not happend...We must download the image data to decoding, and then callback. This order is guranteed.

> Maybe the completion block getting called but it's still decoding the image? Or it's not reasonable?
If the `image` is not nil, it's always get decoded and ready for render on imageView. But the image may from memory cache/ disk cache/ network, does this cause issue ? You can limit the case by checking the `cacheType` enum

> ShimmerIndicator
What actual issue for this ? You means your indicator does not disapper after `stopAnimation ?`

You can check the official demo code here, the `indicator` view does not been removed from superView after `stopAnimation` called. We typycially to hide the indicator view (to avoid re-create for each Cell reuse...), like this: [SDWebImageIndicator.stopAnimation](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDWebImageIndicator.m#L230-L243)

**Comment by CraftizLtd** [comment]
Hey @dreampiggy,

Thank you for responding.
I fixed the issue with the indicator, but the "delayed" loading still happens (only on a slow network).
I got it working for now with a workaround that I keep playing the shimmer effect, but when the photo loaded it's "hiding" the shimmer (z-index wise). Should we close the thread?

**Comment by dreampiggy** [comment]
@CraftizLtd Hi.

Could you please give me a re-producable demo for this ? So that I can test and debug to find the issue. From your description, I guess there are some rare case about the setImage logic and downlaoder logic, but I didn't find a way to re-produce it on my local device.

**Comment by CraftizLtd** [comment]
Hey @dreampiggy , sure. The project is under NDA but I'll strip down all the relevant code, create a private repo and will add you as a collab. Sounds good?

**Comment by CraftizLtd** [comment]
Hey @dreampiggy , I'm close to finishing the sample project (sorry for the delay, took time to strip it). Do you have Skype/Hangouts we can discuss in? I'll guide you through

**Comment by dreampiggy** [comment]
@CraftizLtd It's better if you can just provide a demo to reproduce the issue, don't need to make your entire project open source to me.

I have skype (but rarely use it...I think it's like a voice mail service but not something chat service ?), hangouts (I remember it's dead for personal usage ?), but if you can, please send me mail with your attached demo project, or if you have a better choice you can try that instead.

**Comment by CraftizLtd** [comment]
I'll send it over, no problems :) We can chat via Hangouts.
Should I send it to here: lizhuoli1126@126.com ?

**Comment by dreampiggy** [comment]
It’s OK.

**Comment by CraftizLtd** [comment]
Sent you an invitation (couldn't send it via mail for some reason):
https://github.com/CraftizLtd/layer/invitations

**Comment by CraftizLtd** [comment]
@dreampiggy oh and I send you a request for the chat within hangouts, I have an idea what could be the issue (might be caused by prefetching)

**Comment by CraftizLtd** [comment]
Hey @dreampiggy, How're things going? Did you take a look?

**Comment by dreampiggy** [comment]
> Hey @dreampiggy, How're things going? Did you take a look?

Hi. Sorry for this delay. I'm busying these days. But I can spend some time to check your issue.

If I don't reply you for 2 days, please @me again :)

**Comment by dreampiggy** [comment]
@CraftizLtd Can not build the `master` branch. Which commit or branch can I used in that Demo to re-produce this issue ?

**Comment by CraftizLtd** [comment]
@dreampiggy you have a SDWebImage_issue branch. Let me know if it compiles for you

**Comment by CraftizLtd** [comment]
@dreampiggy Please note, I just pushed to this branch a change (changed the URL compositing) as since then we changed something within the server. Pull before you run :)

**Comment by dreampiggy** [comment]
@CraftizLtd I believe this is a `Cell reusing issue`, but not something logic error.

Your `ShimmerView` is just like a indicator, because you use it with `UICollectionViewCell`, you should understand that each shimmerView should `Reset all its status once the `cellForItemAt:` method get called. Or, your shimmerView will in a wrong status (one cell get disapper from screen and reused from the poll for new cell appear on screen, but its already get called `startShimmer`)

I change the code into this:

```swift
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "TemplateCell", for: indexPath) as! TemplateCollectionViewCell
        let template = templates[indexPath.item]
        
        guard let url = URL(string: template.previewURL) else {
            return cell
        }
        
        cell.previewImage?.sd_imageTransition = .fade
        cell.shimmerView.startShimmer()
        cell.previewImage?.sd_setImage(with: url, completed: { [weak cell] (image, error, cacheType, url) in
            if image != nil {
                cell?.shimmerView.stopShimmering()
            }
        })
        return cell
    }

    func startShimmer() {
        /// Reset all status
        layer.mask = gradient
        gradient.removeAllAnimations()
        gradient.opacity = 1
        
        /// Why these animation setup code is placed there ? Shouldn't put them in `configureAndStartShimmering()` ?
        animation.duration = 1.7
        animation.speed = 1
        animation.repeatCount = 1000
        gradient.add(animation, forKey: "shimmer")
    }
    
    func stopShimmering() {
        gradient.opacity = 0
        gradient.removeAllAnimations()
        layer.mask = nil
    }
```

**Comment by dreampiggy** [comment]
I've pushed the code into that `SDWebImage_Issue` branch.

I think it's not a SDK bug but a Usage issue. If this code still does not fix your problem, you can reply again.

**Comment by Rokata9** [comment]
@dreampiggy Sorry to ping you on an old issue, but is there somewhere an example on custom **SDWebImageIndicator**? Should I assume that I just need to set ```indicatorView``` property inside the implementation class and just hide/show it in ```startAnimatingIndicator```/```stopAnimatingIndicator```? I want to verify with my implementation, which is not working correctly.

**Comment by dreampiggy** [comment]
+ indicatorView: Usually use the lazy property to initialize and config your UIView.
+ startAnimatingIndicator: Called when indicator begins showing (We will also call `hidden = false`). You can play your animation using native API at the same time.
+ stopAnimatingIndicator: Called when indicator stop showing (We will also call `hidden = true`). You can stop your animation using native API at the same time.

For example, you can play https://github.com/airbnb/lottie-ios lottie `LOTAnimationView` using the API. We suggest you to implements `stop` logic, because not all the UIView `hidden=true` will work. Some of UIView will use a driver or timer to refresh and render, which cause CPU time even it not showing.

**Comment by dreampiggy** [comment]
You can learn about SDWebImage's itself implementation using `UIProgressView` and `UIActivityIndicator`:
https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDWebImageIndicator.m#L43

**Comment by Rokata9** [comment]
@dreampiggy Thanks for the quick reply! I checked the source code for the progress and activity indicators, it seems I'm not missing anything important from there.

But there seems to be an issue with the placeholder. **If I don't provide ```placeholderImage```**, in the end the final image is displayed as a thin line, just a few points high.
**If I provide some dummy placeholder**, the final image gets displayed but is resized according to the placeholder's size, not acfording to the size I specify with **```SDImageResizingTransformer```**. Only if I scroll down and back to that item, the image somehow gets refreshed and resized according to its own size (I'm using it in a cell of a ```UITableView```).

**The custom indicator** seems to be also dependent on the placeholder - displayed as a thin line if there's none and according to the placeholer's bounds if there.

The leading/trailing anchors of the image view are to the safe area, but size is set based on the size of image being downloaded (aspect ratio is only known in advance). This is the only code I use from the library:

```
let transformer = SDImageResizingTransformer(size: CGSize(width: scaledWidth, height: scaledHeight), scaleMode: .fill)
...
customCell.wpImage.sd_imageIndicator = ShimmerIndicator()  // just a dummy view with some colored background
customCell.wpImage.sd_setImage(
       with: URL(string: imgUrl),
       placeholderImage: UIImage(named: "someImage"),
       context: [.imageTransformer: transformer]
)
```

I'd appreciate if you can confirm if there's an obvious error in my approach. I'll be looking now at the source of ```sd_setImage```. Thank you!

**Comment by dreampiggy** [comment]
Emm. The placeholder is designed to be `Matching the View`, not `Matching the image`. So it does not provide any context about `How large the loaded image is`. The only context is `The super view or ImageView your placeholder attached`.

If you want to adjust your placeholder based on `Loaded Image size`, you should call the advanced API here:

[-sd_internalSetImageWithURL:placeholderImage:options:context:setImageBlock:progress:completed:](https://sdwebimage.github.io/SDWebImage/Categories/UIView%28WebCache%29.html#/c:objc(cs)UIView(im)sd_internalSetImageWithURL:placeholderImage:options:context:setImageBlock:progress:completed:)

This API provided the loaded image and its context. You can adjust your placeholder right in the `setImageBlock` here.

**Comment by Rokata9** [comment]
Hi @dreampiggy, it was AutoLayout issue indeed, I had to set arbitrary height constant in Interface Builder and update it in ```cellForRowAt``` when I know the image size. Thanks a lot for the hint! 

I have one more question. **How can I best avoid showing the indicator when the image is known to be in the cache (disk or memory)?** Otherwise, there's a quick flash of the indicator just before showing the image (not needed IMO when it's in cache). I realise that to achieve this I have to still read the cache on a background thread and communicate it back to the main thread. Thus, if I delay showing the indicator only for downloads, I'll still have blank image view for a moment before setting the image when it's in the cache. 

The closest I could get is in [this sample commit](https://github.com/Rokata9/SDWebImage/commit/253cc0750ec1cd4d72cbd1908197304050619147) that I made on a fork. Hiding initially the indicator is not an issue, but I needed to also delay ```startAnimatingIndicator``` to when image is resolved or not from cache, instead of starting it immediately [as in the original code]. 

Any guidance would be appreciated, thank you very much for your quick responses.

**Comment by dreampiggy** [comment]
> How can I best avoid showing the indicator when the image is known to be in the cache (disk or memory)?

Sounds like a new feature request. For placeholder image, we already supports this logic by using `setImage in the same runloop without dispatch async to main queue`.

However, seems the indicator does not get the same logic as placeholder image.

I guess this need a patch PR to fix this problem.

**Comment by dreampiggy** [comment]
> How can I best avoid showing the indicator when the image is known to be in the cache (disk or memory)?

The built-in `UIActivityIndicator` works well for cache hit from memory issue. UIKit will not render the indicator because we `start` and `stop` it at the same time.

Does this issue happens because of your own custom indicator implementation ? Which does not follow this rule ?

**Comment by Rokata9** [comment]
There's no issue when the memory cache is hit, as you said we're still on the main thread and don't start background operation. I was wondering more for the case **when the image is in the disk cache only** and respectively when a background operation is started. This time the render loop will commit and another run will be scheduled after short period of time (as long as it takes to read it from the disk). Thus, the flashing indicator.

For the case with the ```placeholderImage``` param I see that if you specify ```SDWebImageDelayPlaceholder``` option, it will only show if the image couldn't be downloaded or loaded from cache due to some error. But not while downloading. Is that correct?

What I was trying to do is to show the indicator only when image has to be downloaded and not show it if it's in memory/disk cache (there's no indicator flash if it's in memory, but it flashes if it's in disk). You can see in the link to the fork that I had to pass some block which shows the indicator, since ```SDWebImageManager``` and ```SDImageCache``` know nothing about UIKit or any other UI framework.
