### ISSUE TITLE
Prefetch cause the gif in modal to stop its animation

### ISSUE THREAD

**Issue by maundytime** [SDWebImage/SDWebImage#2889]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info | Value
---|---
 Platform Name           | iOS
 Platform Version        | 13.3
 SDWebImage Version      | 5.3.1
 Integration Method      | SPM
 Xcode Version           | Xcode Version 11.2.1 (11B53)
 Repro rate              | all the time (100%)
 Repro with our demo prj | n/a
 Demo project link       | https://github.com/maundytime/Demo

### Issue Description and Steps

Reproduce way: Install the demo above, at first vc, I prefetch a gif, then modal second vc, I do pan on it and change it size, the gif will stop animating.

After first installation, the problem is gone, seems that gif data is cached in disk.

Or if I don't prefetch at first installation, the problem is not exist either.

This problem is found when I try to do vc dismiss transition.

Hope for some instructions or suggestions. Thank you : )

**Comment by dreampiggy** [comment]
I try you demo, maybe I get the reason. But at first, I want to talk about some basic background knowledge.

The reason is about the animation behavior of `UIImageView` and `UIAnimatedImage`. Not SDAnimatedImageView.

UIImageView supports animation, you can see these APIs: [startAnimating](https://developer.apple.com/documentation/uikit/uiimageview/1621061-startanimating)
When a UIImage is created by [animatedImage(with:)](https://developer.apple.com/documentation/uikit/uiimage/1624149-animatedimage) API, it's a `UIAnimatedImage`.

UIImageView's animation behavior is: When the view is duration animation (in your ViewController transition), the animation will stop. This is known behavior. (I don't want to tell the details here, but a hint: UIImageView's animation is based on CALayer key-frame animation, when ViewControll transition begins, all CALayer transition will be implicit disable) .You can try your demo by change the type `SDAnimatedImageView` -> `UIImageView`.

However, SDAnimatedImageView does have this behavior. It do animation based on a timer callback and render on CALayer. Until you call `stopAnimating` API, it still get callback and render frame. (note we supports to disable animation when view appears, but this is not related to ViewController transition)

**Comment by dreampiggy** [comment]
So, `Why prefetcher cause issues ?`

It's because, when you call `SDWebImagePrefetcher` with the default arguments, we will not produce `SDAnimatedImage`, we will produce `UIAnimatedImage`. When this `UIAnimatedImage` meet `SDAnimatedImageView`, it will cause the SDAnimatedImageView do the UIImageView based animation behavior. So, it stop when pop viewController.

When `SDAnimatedImageView` call` sd_setImage(:_)` API, it provide a default context option: [.animatedImageClass](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDAnimatedImageView%2BWebCache.m#L63)

When you secondlly query that image, the image is queried from disk cache, and we found that you use the the `animatedImageClass`, and give the `SDAnimatedImage` instead of `UIAnimatedImage`. So the animation does not stop when pop viewController.

To solve the issue, you can do either one of two things (one is OK)

1. If you want to prefetch GIF and render on a `SDAnimatedImageView`, provide the `.animatedImageClass` context option as well.

```swift
SDWebImagePrefetcher.shared.context = [.animatedImageClass : SDAnimatedImage.Self]
```

2. You can try to use this context option: [.matchAnimatedImageClass](https://sdwebimage.github.io/Enums/SDWebImageOptions.html#/c:@E@SDWebImageOptions@SDWebImageMatchAnimatedImageClass), to ensure the image class is matched. So that even the prefetcher cached the `UIImage`, your `sd_setImage(_:)` on `SDAnimatedImageView` call, will ignore that cache, and requery to generate a `SDAnimatedImage`

```swift
SDWebImagePrefetcher.shared.context = [.matchAnimatedImageClass : true]
```

**Comment by maundytime** [comment]
I see, SDAnimatedImage and SDWebImagePrefetcher are independent from each other. So SDWebImagePrefetcher use system UIAnimatedImage as default behavior.

Your two suggestions is sweet and worked. Problem solved.

Thank you very much for reply with so much detail. It would be a huge work for me to figure out this by myself.

**Comment by dreampiggy** [comment]
Actually, this is a good catch for Animation Image View + Prefetcher things. I'll update this point into the documentation, to let user know that prefetch a GIF (used SDAnimatedImageView) should use extra option.

**Comment by dreampiggy** [comment]
@maundytime Updated the wiki about prefetcher and this animated image view. Maybe this can be helpful for other users.

https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#using-sdwebimageprefetcher
