### ISSUE TITLE
Loading image from cache

### ISSUE THREAD

**Issue by YurchukV** [SDWebImage/SDWebImage#2981]
Hello, please tell me how to fix the situation of the bug that is visible on the video. The picture has already been loaded into the cache, but at startup it is substituted.
SDWebImage (5.7.1)
https://www.icloud.com/iclouddrive/0sXyWCVAuk6eXSGEPbFUF6PJw#SDWebImage_placeholderImage

**Comment by dreampiggy** [comment]
+ Startup means, no RAM object is kepted. So query iamge from disk cache.
+ Query disk cache by default, means async
+ Async means, your placeholder will be rendered firstly, then replace with another queried image
+ If your placeholder is nil, a blank image will be rendered.
+ All of these above, result a quick `Flash` during startup.

Can my explanation solve your question ?

**Comment by dreampiggy** [comment]
If you want to avoid this and provide a better experience for user, you can do the following:

1. You can prefetch the image from disk during startup, use `SDWebImagePrefetcher`. See that documentation.
2. You can provide a fade transition animation, or some placeholder, to let user not really visible for this flash back. See `SDWebImageTransition` and placeholder API.
3. You can force to query these first page images from disk synchronizly. You pass the `SDWebImageQueryDiskSync` option for your first page images loading. Note: It's dangerous to use this option in other situation like List View, because query disk need more time (update to 200ms, 60FPS means 16.6ms duration, remember), which may block main thread.
