### ISSUE TITLE
Image prefetching cancel for URL

### ISSUE THREAD

**Issue by ferologics** [SDWebImage/SDWebImage#3012]
Hey, is it possible to cancel prefetching for a specific URL?

**Comment by dreampiggy** [comment]
Cancelling a prefetch ? Did you try use `SDWebImagePrefetcher` ? There are APIs to do this, use the token to cancel, or cancel all the prefetched URLs.

https://sdwebimage.github.io/SDWebImage/Classes/SDWebImagePrefetcher.html

**Comment by ferologics** [comment]
Ah, okay. 

Is there a difference in performance when I prefetch for just one URL and then I generate token for each image? 🆚 batch prefetch. I can't cancel the token per the batch prefetched URL, just all.

**Comment by dreampiggy** [comment]
Batch Prefetch via URLs is a little performent than prefetch each of URL in for-in-loop.

This is implementation details, because that `SDWebImagePrefetchToken` use lock to ensure thread safe internally. Each token will use semaphore, if you prefetch 100 URL in for in loop, you may create 100 semaphore lock, this may cause a little slow performance (not so huge for CPU, but still a cost).

**Comment by ferologics** [comment]
Cool, I’ll do that then :) thanks for your input!
