### ISSUE TITLE
How to set minPixelSize for a downsampled image

### ISSUE THREAD

**Issue by surajrautela** [SDWebImage/SDWebImage#3089]
### New Issue Checklist

* [Yes ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [yes] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [Yes ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Platform Name iOS
Platform Version iOS 12+
SDWebImage Version 5.0.0
Integration Method Carthage/cocoapods
Xcode Version 11

### Issue Description and Steps

So We download an image from web . It can have any aspect ratio ( lets say 200/400)
I need to downsample that image to fit image view . ImageView size = 48*48

When I used "ThumbnailSize" option with a value of CGSize(48,48)  to downsample the image using SDWebImage , the output image had size 24*48.

The web image can be of any aspect ratio 

Is there a way we can get the value of the output downsampled  image to have minPixelSize as 48 . 
In the above example , how can we have image of size (48*96). Currently we get (24*48)

**Comment by dreampiggy** [comment]
Seems....Current we have no such a feature built-in, but there are way to workaround.

What you want is like a `Custom Calculation Block`. You need to get the resolution of current loaded image, and then using some calculation based on resolution and do transform.

You can create a custom `SDWebImageTransformer`. The transformer will receive the input image and you provide a output image. So that you can calculate the size you want, and call some image processing API (like we used in `UIImage+Transform`).

See more: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50

**Comment by dreampiggy** [comment]
Because of different user's use case. Some custom logic like `I want to do aspect ratio which fit the minimum edge of image, not the maxmimux edge of iamge`, may need extra context the options. A better way, it's that we framework provide the customize logic that you can implements and build.

**Comment by dreampiggy** [comment]
This need another context option. Link to feature request from: https://github.com/SDWebImage/SDWebImageSVGCoder/pull/29


Proposal API:

```swift
let contentMode = SDImageScaleMode.aspectFit
let options = [.imageContentMode: contentMode, .maxPixelSize: CGSize(width: 100, height: 100)]
// .preserveAspectRatio option will be deprecarted and removed in the future
let image = ImageCoder.shared.decodedImage(data: data, options: options)
```
