### ISSUE TITLE
Issues downloading images from Backblaze (affects around 1% of our users)

### ISSUE THREAD

**Issue by LW-App** [SDWebImage/SDWebImage#3190]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          ios 
 Platform Version       13.0 - 14.4 (all users affected)
 SDWebImage Version      newest (Mid March '21)
 Integration Method    cocoapods 
 Xcode Version            Xcode 11 
 Repro rate              sometimes 1x% 

### Issue Description and Steps

Hello!
Its a really rare case that users are not able do load the images from our CloudStorage (we use Backblaze).
Around 1-2% of ours users encounter this issue. We did not even notice until Apple most recently reviewed our App. They were not able to see a single image! We use a similar feed to Facebook and they were not able to see the exact same images which worked on our end. They tested it on an iPad and on an iPhone, both with the newest Software version. We tried to reproduce the error but weren't able to do so.
Thats why I show the error which our implemented version of SDWEBIMAGE prints out.

"Optional(Error Domain=SDWebImageErrorDomain Code=2002 \"Operation cancelled by user during sending the request\" UserInfo={NSLocalizedDescription=Operation cancelled by user during sending the request}) + Operation cancelled by user during sending the request"

"Optional(Error Domain=SDWebImageErrorDomain Code=2001 \"Download marked as failed because response status code is not in 200-400\" UserInfo={NSLocalizedDescription=Download marked as failed because response status code is not in 200-400, SDWebImageErrorDownloadStatusCodeKey=404}) + Download marked as failed because response status code is not in 200-400"

The internet was always stable.

our code

            SDWebImageDownloader.shared.config.downloadTimeout = 100
            postImageView.sd_setImage(with: photoUrl, placeholderImage: nil, options: .allowInvalidSSLCertificates) { (image, err, sd, url) in
                self.postImageView.sd_imageIndicator = nil
                self.postImageView.sd_imageIndicator?.stopAnimatingIndicator()
                if err != nil {
                    self.postImageView.image = UIImage(named: "placeholder-image")
                }
            }

we tried also without options ( currently "allowInvalidSSLCertificates") but it did not help.

Any idea?

**Comment by randarnold** [comment]
Can your photoUrl go stale? I have this issue frequently when between the time I download the URL for an image and the time I request it, our backend has updated things and there is now a new URL, and the one I have points to nothing. And I get a 404 response.

Our fix is to not delete the old images so that they can still be referenced.

**Comment by FlaxSupport** [comment]
Hey, 
no images have been deleted so I assume its not the problem. We tested it out downloading (loading the same users feed) and it did not work for the other side but for me. And all pics are addressed uniquely

**Comment by CainLuo** [comment]
Have you solved it now? I also encountered the same problem, the initial suspicion is that the URL address given by the server is faulty. @FlaxSupport

**Comment by FlaxSupport** [comment]
Hey,
It seems to not appear currently.
However, I did not change anything.
Kind regards



Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: CainLuo ***@***.*** ***@***.***> >
Betreff: Re: [SDWebImage/SDWebImage] Issues downloading images from 
Backblaze (affects around 1% of our users) (#3190)
Datum: 12.05.2021, 05:29 Uhr
An: SDWebImage/SDWebImage ***@***.***
***@***.***> >
CC: FlaxSupport ***@***.*** ***@***.***> 
>, Mention ***@***.*** ***@***.***> 
>

Have you solved it now? I also encountered the same problem, the initial 
suspicion is that the URL address given by the server is faulty. 
@FlaxSupport <https://github.com/FlaxSupport>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SDWebImage/SDWebImage/issues/3190#issuecomment-839405695> 
, or unsubscribe
