### ISSUE TITLE
How to use a shared cache for Widget extension on iOS

### ISSUE THREAD

**Issue by spike-hue** [SDWebImage/SDWebImage#3202]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.0
 SDWebImage Version      | 5.11.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.4
 Repro rate              | 
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

This is simply about feature clarification since the documentation isn't very clear.

I want to create a shared image cache to use with my app and a widget extension (`WidgetKit`). It seems this is possible based on this PR https://github.com/SDWebImage/SDWebImage/pull/3066. However, the PR example seems inaccurate since the API mentioned doesn't seem to exist.

#### So far this is what I have done:

1) In my app, I set the `defaultDiskCacheDirectory`. I am not sure if this is correct way to do it cause the PR https://github.com/SDWebImage/SDWebImage/pull/3066 doesn't show this correctly. Here I pass `absoluteString`.
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
     SDImageCache.defaultDiskCacheDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")?.absoluteString
}
```

2) In my widget extension, I want to use the shared cache. Also, I need to fetch images individually so I am trying to create a `SDWebImageManager` to use that shared cache. I am not sure how to do the following:
```swift
import WidgetKit
import SwiftUI
import SDWebImage

struct Provider: TimelineProvider {
    
    // Not sure how to create this to use a shared cache
    let cache = SDImageCache(namespace: "<not sure what to put here>",
                             diskCacheDirectory: FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")?.absoluteString)

    // Not sure how to create this to use a shared cache
    let sdWebImageManager = SDWebImageManager(cache: cache, loader: <not sure what to put here>)

    sdWebImageManager.loadImage(with: url, options: [], progress: nil, completed: { (image, _, _, _, _, _) in
        // I will do something with the image here. I also want this cached in the shared cache with the app.
    })
}

```

The main reason I want a shared cache is because widgets have a `30 mb` limit. I'm hoping this will solve the problem to have a larger cache.
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/10701375/113443688-77551280-93c0-11eb-9e7a-e1cfb7cfcfdd.png">

Could someone help with this please?

**Comment by dreampiggy** [comment]
...

This second screenshot `The main reason I want a shared cache is because widgets have a 30 mb limit. I'm hoping this will solve the problem to have a larger cache.`.

This is noe Disk Size, this is the limit of `RAM`.

Seems Apple does not allows to allocate large memory buffer on watchOS. You can workaround using the `avoidDecodeImage` WebImage options to avoid this decode steps.

I didn't faced this in the previous, actually we can add the `avoidDecodeImage` by default on watchOS.

**Comment by johnswifttt** [comment]
@dreampiggy Thank you for reply. Just to clarify:
1. I am not using `watchOS`. The above example is for a widget on an iPhone (iOS). 
2. Is what I want to do possible with SDWebImage? To share a cache with widget on an iPhone (iOS)?

If this is possible, could you please share example of how to do this? Please see my example above with `SDWebImageManager` that I am trying.

**Comment by johnswifttt** [comment]
@dreampiggy Thank you for reply!! Just to clarify:

1. I am not using `watchOS`. The above example is for a widget on an iPhone (`iOS`) and we do not have a watch app. 
2. Thank you for clarifying this is a `RAM` issue. In regards to sharing a cache with a widget on an iPhone (`iOS`), is this possible with SDWebImage? If this is possible, could you please share a code example of how to do this? Please see my example above with `SDWebImageManager`. I need `SDWebImageManager` because this is what I use to fetch. 

I appreciate any help on this!

**Comment by johnswifttt** [comment]
@dreampiggy Thank you for reply!! Just to clarify:

1. I am not using `watchOS`. The above example is for a widget on an iPhone (`iOS`) and we do not have a watch app. 
2. Thank you for clarifying this is a `RAM` issue. In regards to sharing a cache with a widget on an iPhone (`iOS`), is this possible with SDWebImage? If this is possible, could you please share a code example of how to do this? Please see my example above with `SDWebImageManager`. I need `SDWebImageManager` because this is what I use to fetch. 

It seems that it is best to share a cache because then the app and widget will not refetch the same image. We have lots of images being fetched.

I appreciate any help on this!

**Comment by dreampiggy** [comment]
For sharing the cache between host App and extension widget, your demo code is correct.

The `namespace` arg will create a new folder with its naming inside the `diskCacheDirectory`.

For example, `namespace: "Foo", diskCacheDirectory: "/path/to/diskcache"`, will result a folder `/path/to/diskcache/Foo`.

Actually you can pass anything, if you don't care, just use `"default"`, which is the same as `SDImageCache.shared`

**Comment by dreampiggy** [comment]
But actually, since `SDImageCache.shared` will always use `~/Library/Caches/com.hackemist.SDImageCache/default`, this path. Your code will custom the cache when you query/store from `SDWebImageManager`.


If you directlly call `SDImageCache.shared` with their own APIs, it does not store/query the thing with your custom path. Take attention of those direct call.

There is a draft proposal to move the `diskCacheDirectory` into `SDImageCacheConfig`, so that you can totally control this default cache path via `SDImageCacheConfig.default`

**Comment by johnswifttt** [comment]
@dreampiggy You're the best! Thanks for answering!!

It looks like the crash has stopped by simply adding `avoidDecodeImage` option for `SDWebImageManager.loadImage`. This is the code so far:

```swift
import WidgetKit
import SwiftUI
import SDWebImage

struct Provider: TimelineProvider {
    private let sdWebImageManager = SDWebImageManager.shared
    
    func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> Void) {
      sdWebImageManager.loadImage(with: url, options: [.avoidDecodeImage], progress: nil, completed: { (image, _, _, cacheType, _, _) in
          // I will do something here 
      })
    }
}
```

Some follow up questions:
1. I notice that `cacheType` for the completion of `SDWebImageManager.loadImage` sometimes returns `memory`. Do you think for widget I should never cache to memory because of `30 MB` limit? For example, I seen that I could do this `SDImageCache.shared.config.shouldCacheImagesInMemory = false` to only use disk. Would you recommend this?
2. Even though crashing is solved, do you think I should still share the cache between the app and widget? Maybe this is best because the app and widget use all the same images so not good to download twice, once for app and once for widget. In the example here I am using `SDWebImageManager.shared`.

**Comment by dreampiggy** [comment]
> For example, I seen that I could do this SDImageCache.shared.config.shouldCacheImagesInMemory = false to only use disk. Would you recommend this?

This will cause each time load image from disk, which may cause async render (and may flash when you quick scroll). If your extension App don't care.

Or, you can just use the `SDWebImageContextQueryCacheType` and `SDWebImageContextStoreCacheType` to control individual image requests, whether query from memory/disk/both or store into memory/disk/both/none

**Comment by johnswifttt** [comment]
@dreampiggy Thanks for response! 

So I think there is a problem when using `SDWebImageManager.shared` in a widget on iPhone (`iOS`). By default, the cache type could be `all`, `disk`, `memory`, or `none`. Everything works but when the image is retrieved from cache type `disk` or `none` then the image does not always show properly. If the image comes from cache type `memory` then it always works. 

Maybe it could be because of the disk cache path for the widget on iPhone (`iOS`)? I accessed the disk path like this:
```swift
let cache = SDWebImageManager.shared.imageCache as! SDImageCache
print(cache.diskCachePath)
```

The path printed is:
```
/Users/j/Library/Developer/CoreSimulator/Devices/F465AEBC-D8C0-44C0-B42B-8698A9BCA24D/data/Containers/Data/PluginKitPlugin/613BDE64-1A69-4818-86B3-646D1C2622DF/Library/Caches/com.hackemist.SDImageCache/default
```

This path is not the shared App Group container. The path is in the `PluginKitPlugin` directory which might be an issue? 

If it helps, this is my code example. Below is Apple's API called `getTimeline` function. Here I fetch all images with `SDWebImageManager.shared.loadImage`. Then the widget changes the image every 1 minute. This change every 1 minute only works if cache type is `memory`. If the cache type is `disk` or `none` then the first image shows, but then does not refresh every 1 minute. Note: I use `DispatchGroup` because I need to download more than one image.

```swift
import WidgetKit
import SwiftUI
import SDWebImage

struct Provider: TimelineProvider {
    private let sdWebImageManager = SDWebImageManager.shared
    
    func getTimeline(in context: Context, completion: @escaping (Timeline<ArtEntry>) -> Void) {
        var entries: [ArtEntry] = []
        
        var minuteOffset = 0
        
        let dispatchGroup = DispatchGroup()
        
        fetchDataFromAPI() { arts in
            for art in arts {
                dispatchGroup.enter()
                
                guard let url = URL(string: art.image) else {
                    dispatchGroup.leave()
                    continue
                }
                
                sdWebImageManager.loadImage(with: url, options: [.avoidDecodeImage], progress: nil, completed: { (image, _, _, sdImageCacheType, _, _) in
                    if let image = image {
                        let entry = ArtEntry(date: entryDate, art: art, image: image)
                        entries.append(entry)
                        minuteOffset += 1
                    } else {
                        print("Did not get image")
                    }
                    
                    dispatchGroup.leave()
                    print("Fetched image. The cache: \(sdImageCacheType.rawValue))")
                })
            }
            
            dispatchGroup.notify(queue: .main) {
                let timeline = Timeline(entries: entries, policy: .atEnd)
                completion(timeline)
                print("Done")
            }
        }
    }
}
```

Any thoughts on this?

**Comment by dreampiggy** [comment]
> This path is not the shared App Group container. The path is in the PluginKitPlugin directory which might be an issue?

It's the issue.

For both plugin and host, you must config the SDImageCache with the same diskCachPath. Not only one. So that they can write/read to the same cache.

**Comment by johnswifttt** [comment]
@dreampiggy Hmm so I just tried a shared App Group but it's not working. 

Here is the code:

In main app in App Delegate:
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
     SDImageCache.defaultDiskCacheDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")?.absoluteString
}
```

In iOS Widget extension
```swift 
import WidgetKit
import SwiftUI
import SDWebImage

struct Provider: TimelineProvider {
    private let sdWebImageManager: SDWebImageManager

    init() {
        let cache = SDImageCache(namespace: "hello", diskCacheDirectory: FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")!.absoluteString)
        cache.config.shouldCacheImagesInMemory = false // For testing disk cache, I turn this to false
        let manager = SDWebImageManager(cache: cache, loader: SDImageLoadersManager.shared)
        sdWebImageManager = manager
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<ArtEntry>) -> Void) {

      // I use all above from other comment here
      sdWebImageManager.loadImage(with: url, options: [.avoidDecodeImage], progress: nil, completed: { (image, _, _, sdImageCacheType, _, _) in
        //
      }
    }
}
```

After downloading images for widget, it seems the directory `hello` is not created here in App Group container:
<img width="1916" alt="path" src="https://user-images.githubusercontent.com/10701375/114102062-abcf3f80-9894-11eb-898b-571ecc94856e.png">


If I print the path:
```swift
let cache = manager.imageCache as! SDImageCache
print(cache.diskCachePath)
```

This is the path I get:
```
file:/Users/j/Library/Developer/CoreSimulator/Devices/7FF42CD2-75A2-4F28-B2B5-2F8C1255D84A/data/Containers/Shared/AppGroup/70A1BF56-FC63-4498-AF94-6F91C6E5B84C/hello
```

It is weird that the path prints with `hello` directory but is not in the container. 

I tried looking for documentation for this but can't find any. Any thoughts on how to make this work?

**Comment by johnswifttt** [comment]
@dreampiggy Hmm so I just tried a shared App Group but it's not working. 

Here is the code:

In main app in App Delegate:
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
     SDImageCache.defaultDiskCacheDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")!.absoluteString
}
```

In iOS Widget extension
```swift 
import WidgetKit
import SwiftUI
import SDWebImage

// Global property for testing
let sdWebImageManager: SDWebImageManager = {
    let cache = SDImageCache(namespace: "hello",
                             diskCacheDirectory: FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.BraveNewLogic.Motivate")!.absoluteString)
    cache.config.shouldCacheImagesInMemory = false
    let manager = SDWebImageManager(cache: cache, loader: SDImageLoadersManager.shared)
    return manager
}()

struct Provider: TimelineProvider {

    init() {
        //
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<ArtEntry>) -> Void) {

      // I use all above from other comment here
      sdWebImageManager.loadImage(with: url, options: [.avoidDecodeImage], progress: nil, completed: { (image, _, _, sdImageCacheType, _, _) in
        //
      }
    }
}
```

After downloading images for widget, it seems the directory `hello` is not created here in App Group container:
<img width="1916" alt="path" src="https://user-images.githubusercontent.com/10701375/114102062-abcf3f80-9894-11eb-898b-571ecc94856e.png">


If I print the path:
```swift
let cache = manager.imageCache as! SDImageCache
print(cache.diskCachePath)
```

This is the path I get:
```
file:/Users/j/Library/Developer/CoreSimulator/Devices/7FF42CD2-75A2-4F28-B2B5-2F8C1255D84A/data/Containers/Shared/AppGroup/70A1BF56-FC63-4498-AF94-6F91C6E5B84C/hello
```

It is weird that the path prints with `hello` directory but is not in the container. 

I tried looking for documentation for this but can't find any. Any thoughts on how to make this work?

**Comment by johnswifttt** [comment]
@dreampiggy Hmm so I just tried a shared App Group but it's not working. 

Here is the code:

In main app in App Delegate:
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
     SDImageCache.defaultDiskCacheDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")!.absoluteString
}
```

In iOS Widget extension
```swift 
import WidgetKit
import SwiftUI
import SDWebImage

// Global property for testing
let sdWebImageManager: SDWebImageManager = {
    let cache = SDImageCache(namespace: "hello",
                             diskCacheDirectory: FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")!.absoluteString)
    cache.config.shouldCacheImagesInMemory = false // For testing disk cache in widget, I turn this to false
    let manager = SDWebImageManager(cache: cache, loader: SDImageLoadersManager.shared)
    return manager
}()

struct Provider: TimelineProvider {

    init() {
        //
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<ArtEntry>) -> Void) {

      // I use the code from other comment above here. 
      sdWebImageManager.loadImage(with: url, options: [.avoidDecodeImage], progress: nil, completed: { (image, _, _, sdImageCacheType, _, _) in
        //
      }
    }
}
```

After downloading images for widget, it seems the directory `hello` is not created here in App Group container:
<img width="2139" alt="path" src="https://user-images.githubusercontent.com/10701375/114103617-74ae5d80-9897-11eb-9071-f7e59d07e5eb.png">

If I print the path:
```swift
let cache = sdWebImageManager.imageCache as! SDImageCache
print(cache.diskCachePath)
```

This is the path I get:
```
file:/Users/j/Library/Developer/CoreSimulator/Devices/7FF42CD2-75A2-4F28-B2B5-2F8C1255D84A/data/Containers/Shared/AppGroup/24EC2410-4673-46B1-BADA-9D22563B4855/hello
```

It is weird that the path prints with `hello` directory but is not in the container. 

I tried looking for documentation for this but can't find any. Any thoughts on how to make this work?

**Comment by dreampiggy** [comment]
> It is weird that the path prints with hello directory but is not in the container.

Seems Apple limit that you should only write to the container's `Library/Cahces` folder ? Not the root folder.

>  The system creates only the Library/Caches subdirectory automatically, but you can create others yourself if you need them. You are free to use the group directory as you see fit, but take care to coordinate its structure among all the group's apps.

Try this ? Or any demo here to let me investigate ?

```swift
FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName").appending("Library/Caches")
```

**Comment by dreampiggy** [comment]
Seems SDWebImage does not automatically create disk cache folder if you pass custom `diskCachePath` ...

**Comment by johnswifttt** [comment]
> Try this ? Or any demo here to let me investigate ?

@dreampiggy Looks the sample you asked can't be done in this manner

<img width="1727" alt="Screen Shot 2021-04-09 at 11 03 12 AM" src="https://user-images.githubusercontent.com/10701375/114200412-30689f00-9923-11eb-9153-44e7ee04ac56.png">

> Seems SDWebImage does not automatically create folder if not exists when you pass custom diskCachePath ...

Does this mean there is a bug in SDWebImage?

**Comment by dreampiggy** [comment]
You can convert it into String and use appending.

Just psedocode, I just means: Use the disk cache folder which already exists (SD does not create one for now).

If it's this issue, I can just create PR to automatically create the folder from your input `diskCachePath` arg if it not exist.

**Comment by dreampiggy** [comment]
Still...Can you provide an demo ? Not just snippet code, a full Xcode project for me to reproduce and debug with.

**Comment by dreampiggy** [comment]
@johnswifttt I found there are also one API:

https://sdwebimage.github.io/SDWebImage/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(cpy)defaultDiskCacheDirectory

Can you use this API instead of changing the cache instance ? Seems I forgot this API.

**Comment by johnswifttt** [comment]
> Just pseudocode, I means: Use the disk cache folder which already exists (SD does not create one for now). For that example, Apple create the Library/Caches in the group container sandbox folder.

I added this in both App Delegate and app extension:
```
SDImageCache.defaultDiskCacheDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.MyApp.MyAppName")!.absoluteString.appending("Library/Caches")
```

The path printed out is: 
```
file:/Users/j/Library/Developer/CoreSimulator/Devices/7FF42CD2-75A2-4F28-B2B5-2F8C1255D84A/data/Containers/Shared/AppGroup/13875607-5B39-4253-B35B-76F3523BC21D/Library/Caches/default
```

However this does not work and I see no folder or images.

> Can you use this API instead of changing the cache instance ? Seems I forgot this API.

Please see above example. I use this new API `SDImageCache.defaultDiskCacheDirectory` but not working in app extension.

> Still...Can you provide an demo ? Not just snippet code, a full Xcode project for me to reproduce and debug with.

I think all you would need to do is create a new Xcode project and widget extension. Then use `SDWebImageManager.shared`. When images come from `disk` then nothing appears.

Is that something you already have a demo of?

**Comment by johnswifttt** [comment]
@dreampiggy could you give any update on this? It seems anyone using SDWebImage in an extension will have the same problems

Thank you!

**Comment by dreampiggy** [comment]
@johnswifttt Test without any issue. Check your code again.

See this demo:

I guess the problem is that, you trigger the `SDImageCache.default` been initialized, before you setup the `SDImageCache.defaultDiskCacheDirectory`.

For example, when you call `SDWebImageManager.shared`, the `SDImageCache.default` will be initialized, DO NOT do this.

Instead, config the `SDImageCache.defaultDiskCacheDirectory` just in the Widget's first setup code line, do not call any other thing.

See screenshot for the demo:

+ App (Write the Image)

![image](https://user-images.githubusercontent.com/6919743/116196543-3acdca00-a766-11eb-9060-c7efd5cd65a9.png)

+ Widget Extension (Read the Image)

![image](https://user-images.githubusercontent.com/6919743/116196685-6650b480-a766-11eb-841f-a2a45d13ec48.png)


+ Demo (Run `Pod Install`):

[SDExtensionSharing.zip](https://github.com/SDWebImage/SDWebImage/files/6382398/SDExtensionSharing.zip)

**Comment by dreampiggy** [comment]
Common mistake like this:

![image](https://user-images.githubusercontent.com/6919743/116196722-6ea8ef80-a766-11eb-8036-9402fb5377ac.png)

This triggers the `SDImageCache.shared` initialized, before the `defaultDiskCacheDirectory` setup.

**Comment by johnswifttt** [comment]
@dreampiggy wow yeah I would not have known that without your help! Sorry if my code examples were not very helpful above. It is finally working!!!

I created a Version 2 of your sample project:
[SDExtensionSharing-Version-2.zip](https://github.com/SDWebImage/SDWebImage/files/6400920/SDExtensionSharing-Version-2.zip)

Last thing, could you see if this is ok in Version 2 project please:
- In extension/widget, I moved setup of `defaultDiskCacheDirectory` to `init` (it was in `getTimeline` before)
- In main app, I moved setup of `defaultDiskCacheDirectory` to `AppDelegate` inside of `didFinishLaunchingWithOptions` (it was in `ViewController` before)
- I show an example of fetching data with `sdWebImageManager.loadImage` and I need to use `DispatchGroup`. Does this look good to you?

**Comment by johnswifttt** [comment]
@dreampiggy Wow I would not have known that without your help! Sorry if my code examples were not very helpful above. It is finally working!!!

I created a Version 2 of your sample project:
[SDExtensionSharing-Version-2.zip](https://github.com/SDWebImage/SDWebImage/files/6401001/SDExtensionSharing-Version-2.zip)

Last thing, could you see if this is ok in Version 2 project please:
- In extension/widget, I moved setup of `defaultDiskCacheDirectory` to `init` (it was in `getTimeline` before)
- In main app, I moved setup of `defaultDiskCacheDirectory` to `AppDelegate` inside of `didFinishLaunchingWithOptions` (it was in `ViewController` before)
- I show an example of fetching data with `sdWebImageManager.loadImage` and I need to use `DispatchGroup`. Does this look good to you?
