### ISSUE TITLE
请教下如果让cell中各个gif保持动画进度同步

### ISSUE THREAD

**Issue by wdq123550** [SDWebImage/SDWebImage#3449]
如果我有很多cell，然后cell中有sdAnimationImageView来播放gif。如何在滑动的时候保持整体的动画同步呢。。。。

**Comment by dreampiggy** [comment]
Current there are no such a issue. SDAnimatedImage designed to work `one image with different state (imageView)`...

If you want to sync the state of playing, maybe we can treat this as a feature request.

**Comment by dreampiggy** [comment]
A possible solution is to use something like Animation Group, or Frame Pool. (In general speaking)

In the same pool, the index and frames access is shared, so each imageView should play at the same speed and frame delay. Looks identical.

For current, seems you have to use `UIImageView` which receive a array of frames predecoded, so that it always play the same (pay attention this may consume more RAM)

**Comment by dreampiggy** [comment]
Now we have Frame Pool: https://github.com/SDWebImage/SDWebImage/releases/tag/5.16.0

But you still need some code to make it work.

```
// When cell re-use or sometime you want to start
for (SDAnimatedImageView *imageView in imageViews) {
    imageView.resetFrameIndexWhenStopped = YES;
    imageView.clearBufferWhenStopped = YES;
    [imageView.player seekToFrameAtIndex:0 loopCount:0]; // Make sure they start at the same time
}

```
