### ISSUE TITLE
ImageView will cancel same pictures loading, if the previous picture has not been loaded yet.

### ISSUE THREAD

**Issue by mTz0206** [SDWebImage/SDWebImage#3568]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps
When you have a ImageView in your tableview cell.
1.The page landing API responds and set image url to the imageView, SD start( T0) to load the picture(100ms).
2. at T0 + 50 ms, some logic trigger tableView reload, the previous picture still in loading, and a same imageUrl was set to it, SD will cancel current operation and restart a new one to load this picture.
3. in Charles you can see below case 
<img width="348" alt="Screenshot 2023-07-24 at 4 28 59 PM" src="https://github.com/SDWebImage/SDWebImage/assets/11922048/b18bc884-a415-42f7-9f5a-164fbed36ed7">
<img width="357" alt="Screenshot 2023-07-24 at 4 30 38 PM" src="https://github.com/SDWebImage/SDWebImage/assets/11922048/1bf10be9-2875-4f13-a3e4-1453e0d2d7f1">
it is called by 
```
- (void)sd_cancelImageLoadOperationWithKey:(nullable NSString *)key {
    if (key) {
        // Cancel in progress downloader from queue
        SDOperationsDictionary *operationDictionary = [self sd_operationDictionary];
        id<SDWebImageOperation> operation;
        
        @synchronized (self) {
            operation = [operationDictionary objectForKey:key];
        }
        if (operation) {
            if ([operation conformsToProtocol:@protocol(SDWebImageOperation)]) {
                [operation cancel];
                printf(@"@#@ - cancel");
            }
            @synchronized (self) {
                [operationDictionary removeObjectForKey:key];
            }
        }
    }
}
```
I can understand it could be used for load different pictures, but for same pictures I think it is better to avoid duplicated loading, it will delay the customer see the image.

Please help correct me, if there is something I misunderstand, thanks.

**Comment by dreampiggy** [comment]
Designed behavior. Current `Load` is bind with `URLSesssion HTTP Request`.

Since during UITableViewCell/UICollectionViewCell, Cell has `reuse` design, if you scroll into another new cell content, you actually `Cancel the previous Load`, which trigger `Cancel URLSession HTTP Request`...

If you have better design or idea about this whole Image Loading Pipeline for `UITableViewCell/UICollectionViewCell`, you can fire your solution here.

**Comment by dreampiggy** [comment]
> some logic trigger tableView reload, the previous picture still in loading, and a same imageUrl was set to it

You need find a better way to gurantee that the usage is not effected by this. Because

1. operation1 = sd_setImage(with: url1)
2. operation2 = sd_setImage(with: url1)

Should I return the same operation instance (means `SDWebImageCombinedOperation`) on this ? Should I effect the rendering part logic, like the `sd_imageIndicator` and `sd_imageTransition` ?

We can not just like to record a `imageView.sd_lastURL` and directly return if `new loaded url isEqual: to the last URL`, which may cause some un-designed behavior and break user's code.

**Comment by dreampiggy** [comment]
And a super tricky usage case is that `SDWebImageRefreshCached`, which means

If `server change the HTTP URL's point to contents, during you two same URL call`...Does we need to cancel the previous request ?

**Comment by mTz0206** [comment]
Thanks @dreampiggy, you response so quick, 
As I check SD's logic, 
 I think there are two cases in UIView loading image
1. one view loads multiple pictures
   sub case 1. load same url 
   sub case 2. load different urls
2. multiple views load multiple pictures
   sub case 1. load same url 
   sub case 2. load different urls

we could  treat case `1.1 one view load same url` same as case `2.2` 
we could use **SDWebImageDownloader** 's `reuse the download operation` logic to avoid picture duplicated  loading request.
```
- (nullable SDWebImageDownloadToken *)downloadImageWithURL:(nullable NSURL *)url
                                                   options:(SDWebImageDownloaderOptions)options
                                                   context:(nullable SDWebImageContext *)context
                                                  progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
                                                 completed:(nullable SDWebImageDownloaderCompletedBlock)completedBlock {
...
    NSOperation<SDWebImageDownloaderOperation> *operation = [self.URLOperations objectForKey:url];
    // There is a case that the operation may be marked as finished or cancelled, but not been removed from `self.URLOperations`.
    if (!operation || operation.isFinished || operation.isCancelled) {
...
    } else {
        // When we reuse the download operation to attach more callbacks, there may be thread safe issue because the getter of callbacks may in another queue (decoding queue or delegate queue)
        // So we lock the operation here, and in `SDWebImageDownloaderOperation`, we use `@synchonzied (self)`, to ensure the thread safe between these two classes.
...
   }
}
```
Then the code change should be like below, and one more code I am not sure, in current logic `sd_internalSetImageWithURL` will call `sd_cancelImageLoadOperationWithKey` twice.
**ASIS**
```
- (void)sd_internalSetImageWithURL:(nullable NSURL *)url
                  placeholderImage:(nullable UIImage *)placeholder
                           options:(SDWebImageOptions)options
                           context:(nullable SDWebImageContext *)context
                     setImageBlock:(nullable SDSetImageBlock)setImageBlock
                          progress:(nullable SDImageLoaderProgressBlock)progressBlock
                         completed:(nullable SDInternalCompletionBlock)completedBlock {
...
    [self sd_cancelImageLoadOperationWithKey:validOperationKey];
...
}
```
**TOBE**
```
- (void)sd_internalSetImageWithURL:(nullable NSURL *)url
                  placeholderImage:(nullable UIImage *)placeholder
                           options:(SDWebImageOptions)options
                           context:(nullable SDWebImageContext *)context
                     setImageBlock:(nullable SDSetImageBlock)setImageBlock
                          progress:(nullable SDImageLoaderProgressBlock)progressBlock
                         completed:(nullable SDInternalCompletionBlock)completedBlock {
...
    if (url != self.sd_imageURL) {
        [self sd_cancelImageLoadOperationWithKey:validOperationKey];
    }
...
}
```
**ASIS**
```
- (void)sd_setImageLoadOperation:(nullable id<SDWebImageOperation>)operation forKey:(nullable NSString *)key {
    if (key) {
        [self sd_cancelImageLoadOperationWithKey:key];
        if (operation) {
            SDOperationsDictionary *operationDictionary = [self sd_operationDictionary];
            @synchronized (self) {
                [operationDictionary setObject:operation forKey:key];
            }
        }
    }
}
```
**TOBE**
```
- (void)sd_setImageLoadOperation:(nullable id<SDWebImageOperation>)operation forKey:(nullable NSString *)key {
    if (key) {
        //remove cancel
        if (operation) {
            SDOperationsDictionary *operationDictionary = [self sd_operationDictionary];
            @synchronized (self) {
                [operationDictionary setObject:operation forKey:key];
            }
        }
    }
}
```

**Comment by dreampiggy** [comment]
Your design seems choose to `Start a new Image Loading Pipeline, but not cancel previous Image Loading`:

There are also another solution: `Do not start a new Image Loading Pipeline, just setImage:placeholder and return, let previous Image Loading Pipeline finish and setImage:newDownloadedImage`

We can analysis which one is more suitable for your case. They have two different implementation and limit

**Comment by dreampiggy** [comment]
You can try to create a PR and run unit tests to check the behavior.

**Comment by mTz0206** [comment]
> Your design seems choose to `Start a new Image Loading Pipeline, but not cancel previous Image Loading`:
> 
> There are also another solution: `Do not start a new Image Loading Pipeline, just setImage:placeholder and return, let previous Image Loading Pipeline finish and setImage:newDownloadedImage`
> 
> We can analysis which one is more suitable for your case. They have two different implementation and limit

I also considered that solution, but I think it could be break the caller's expectation，
normally, when we call image load function, no matter success or failed , it will always call back,
but if we return directly in this case , caller's completedBlock will not be called, that could be confusing.
and , if we also execute the completedBlock when return, it is also confusing, it is called before the previous completedBlock.
so base on above consideration , I choose to keep the image loading pipeline and treat is as cache image loading case.

**Comment by dreampiggy** [comment]
After think your changes. Seems this still contains issue.

This change break the assumtation:

1. One Image Load pipeline (which means, `<image, KeyPath, url>`) can be duplicated.
Because if you don't cancel the exact same `URL and setImageOperationKey` on the same image view, then these API will cause problem:


1. `imageView.sd_imageOperationForKey:` is not equal to the return value of sd_internalSetImage. You can not distinguish from multiple operations. Which break the API design
2. `imageView.sd_imageLoadStateForKey:` will cause issue, because actually there are two load state `One for previous image load pipeline, another for current image load pipeline`.

**Comment by dreampiggy** [comment]
@mTz0206  Think you Changes as SwiftUI

Is this follows `A Single Source of Truth` ? https://www.kodeco.com/11781349-understanding-data-flow-in-swiftui

No, because the `Source of Truth` for imageView, is `URL`, but you internally start `multiple image request pipeline` , which is wrong.

When the `URL` not changed, you actuall should not trigger any image load pipeline, instead of hacking to assume `multiple image load pipeline which looks the same`

**Comment by dreampiggy** [comment]
@mTz0206 Email me and I use IM to talk to you about the design issue.

I think the good way to support `continue download`, is not effect the `cancel previous image loading` design.

But instead, we should support Resuable HTTP download, see #https://github.com/SDWebImage/SDWebImage/issues/867
Which need `NSURLSessionDownloadTask`, not `NSURLSessionDataTask`, because we need to keep the partial data when we cancel. And resume it when same URL query.

But it's still need `1. cancel, 2. request`, we can not just skip `1. cancel`
