### ISSUE TITLE
Support HEIC Sequence image encoding via `public.heics` UTI but not `public.heic` UTI for App compatibility

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImage#3726]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Feature requests

Apple's ImageIO in iOS 18 expose the public API for: https://developer.apple.com/documentation/uniformtypeidentifiers/uttype-swift.struct/heics

It's back-deployed supported on iOS 16-17 as well.

Currently our `SDImageHEICCoder` does not support animated image encoding. It's time to update and provide the support by ImageIO framework

CC @VaslD

**Comment by VaslD** [comment]
To continue discussion, I've only run encoding on my iOS 17.5.1 and macOS 14.5 (real device, through Xcode 15.4). I asked some colleague to print me `CGImageDestinationCopyTypeIdentifiers()` from their iOS 14/15 devices and I've seen `"public.heics"` support being reported. Given that the API is the same I should expect encoding JustWorks™ on legacy systems.

I can double check by running real encoding on device for 14 through 17 (hopefully) iOSes by tomorrow and get some statistics.

**Comment by VaslD** [comment]
I ran this demo on the following devices/simulators. It read bundled 300-something frames (extracted from a wildlife video by FFmpeg) and encoded a single HEICS.

[HEICS.zip](https://github.com/user-attachments/files/16191093/HEICS.zip)

| Device      | OS            | Supported | Time Elapsed |
|-------------|---------------|-----------|--------------|
| iPhone15,4  | iOS 18 Beta 2 | NO        |              |
| iPhone15,4  | iOS 17.1.1    | YES       | 1.71 s       |
| iPhone16,1  | iOS 17.0      | YES       | 1.38 s       |
| iPhone14,7  | iOS 16.3      | YES       | 3.71 s       |
| iPhone15,3  | iOS 16.1.1    | YES       | 3.98 s       |
| iPhone13,4  | iOS 15.3.1    | YES       | 3.99 s       |
| iPhone13,2  | iOS 14.7.1    | YES       | 4.00 s       |
| Simulator   | iOS 17.2      | YES       | 43.35 s      |
| MacBook Pro | macOS 14.5    | YES       | 1.07 s       |

The iOS app was compiled with Xcode 15.2, and Simulator/Mac tests were run in Xcode 15.4.

You were right about Simulator lacking hardware acceleration and performance took a big hit.

Surprisingly the app failed to encode a valid HEICS on iOS 18 Beta 2 (when deployed by Xcode 15.2). I'm guessing it's an ImageIO bug in the beta, because the code and sample input images were all the same (bundled in app) and all functions exited with success. On iOS 18, CGImageDestination data/file remained 0 byte however even after final call to `CGImageDestinationFinalize()` returned true.

**Comment by dreampiggy** [comment]
@VaslD I found some interesting behavior. Seems iOS 17 and iOS 18 have different behavior on ImgeIO for HEICS encoding.

### iOS 18

+ Use `public.heic` can successfully encode animated heics on simulator, results in `non-animated` HEIC (even the API `CGImageDestinationFinalize` return true)
+ Use `public.heics` can not successfully encode animated heics on simulator (beta3), which always return 0 bytes buffer.



### iOS 17

+ Use `public.heic` can successfully encode animated heics on simulator, results in `non-animated` HEIC (even the API `CGImageDestinationFinalize` return true)
+ Use `public.heics` can successfully encode animated heics on simulator

![image](https://github.com/user-attachments/assets/92d1c93b-25d8-46bd-b13a-9f60e16d7651)


These behavior now confusing me. I don't know whether it's iOS 18 beta bug or something

**Comment by dreampiggy** [comment]
And, acutally your previous `SDWebImage does not support encoding HEIC sequences image` is wrong.

The encoded image using `public.heic` can actually been decoded by ImageIO itself. Even the `CanAnimate` meta is NO. It reports as animated image.

The actually description is that `SDWebImage encoded HEIC sequence image can not been consumed by other Application such as MacOS Preview.app`😂

**Comment by dreampiggy** [comment]
I think it's a feature which only HEIC has.

***Multiple-frames Image** != **Animated Image**

A image can contains multiple frames, but whether it's `Animated` or not, is another thing.

This concept breaks SDWebImage (and me)'s own concept. We always assume `multiple frames == animated)

**Comment by VaslD** [comment]
This is what I was trying to say from the start (in the original issue). Animated HEIC is actually HEICS. (That there is no such thing as animated HEIC.)

**Comment by VaslD** [comment]
I don't think you test above is entirely valid. Although I do agree with the result.

When you use `public.heic` to encode images, you *should* use `*.heic` extension; conversely when you use `public.heics`, the file name extension *should* be `*.heics`. It doesn't matter how many images you encode (static frame or image sequence), or whether original images are expected to animated. HEIC and HEICS probably use (somewhat or entirely) different underlying file format, you cannot expect a file to start animating just by changing the file name extension to `*.heics`.

**Comment by dreampiggy** [comment]
Really ? We don't care file name at all.

We always use data buffer and in-memory to represent "Animated Image"

I think you use SDWebImage somehow as a `general image encoder`, which may be more cases which the SDK does not considerated at the design time.

**Comment by dreampiggy** [comment]
Anyway, any idea about that #3727 ?
