### ISSUE TITLE
Smoothy scrolling issue

### ISSUE THREAD

**Issue by haxinc** [SDWebImage/SDWebImage#566]
Hi ..

I used SDWebImage for asyn cell.imageview , I used the simple code as

[cell.imageView setImage .......];

inside cellforRowAtIndexPath

but when I continue scrolling fast the performance of the app has been slowly and flooded!!

what is the best way to show the images from remote server without issue of scrolling or performance ..

Thanks

**Comment by JPROFFICIAL** [comment]
@bpoplauschi Im referring back to this post because I have been time-profiling the app and came to this. This is the main line thats causing the scrolling to drop frames (As far as I can tell). Not sure if this is happening because of the size of the images (each are from 1 - 1.5 mb)? I read a closed issue on here regarding bigger image sizes, but am not sure if this would apply.

Thanks for your response! Fantastic framework.
![screen shot 2016-05-09 at 10 10 26 am](https://cloud.githubusercontent.com/assets/14960440/15117709/64342ea4-15ce-11e6-8acd-4ae6ec3a8bea.png)

**Comment by bpoplauschi** [comment]
Yeap, it looks fair, if the images are that large.

**Comment by JPROFFICIAL** [comment]
@bpoplauschi I really appreciate the quick response time, thanks alot. What would you recommend for getting the image sizes smaller? Is this something that can be done by a SDWebImg function? possibly caching them smaller?

**Comment by mythodeia** [comment]
basically there are 2 options:
1. getting the images smaller from the server side
2. try [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.h#L126) to reduce the size of the image first before caching.

**Comment by JPROFFICIAL** [comment]
Thanks alot both of you!! Big ups on the lib its fantastic.
