### ISSUE TITLE
Wrong handling of 304 status code

### ISSUE THREAD

**Issue by Krivoblotsky** [SDWebImage/SDWebImage#846]
I'm sending "If-Modified-Since" header to download images only if remote ones changed. 
(I've setup my custom NSURLProtocol, but I think, this does not matter).

I've checked 

```
- (void)connection:(NSURLConnection *)connection didReceiveResponse:(NSHTTPURLResponse *)response
```

in SDWebImageDownloaderOperation and I see the status code is 304, which is ok.

But, I'm receiving NSError:

```
Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo=0xdd6fca0 {NSLocalizedDescription=Downloaded image has 0 pixels}
in completion block of SDWebImageManager.
```

Expected result:
Completion block returns cached image (if exists). (Like in case when operation is cancelled).

Here the quick workaround, but I think you can do it more elegant:

```
- (void)connection:(NSURLConnection *)connection didReceiveResponse:(NSHTTPURLResponse *)response {

    if ((![response respondsToSelector:@selector(statusCode)]
         || [((NSHTTPURLResponse *)response) statusCode] < 400)
        && [((NSHTTPURLResponse *)response) statusCode] != 304) {
        NSInteger expected = response.expectedContentLength > 0 ? (NSInteger)response.expectedContentLength : 0;
        self.expectedSize = expected;
        if (self.progressBlock) {
            self.progressBlock(0, expected);
        }

        self.imageData = [[NSMutableData alloc] initWithCapacity:expected];
    }
    else {
        NSUInteger code = [((NSHTTPURLResponse *)response) statusCode];
        if (code == 304) {
            [self cancelInternal];
        } else {
            [self.connection cancel];
        }
        [[NSNotificationCenter defaultCenter] postNotificationName:SDWebImageDownloadStopNotification object:nil];

        if (self.completedBlock) {
            self.completedBlock(nil, nil, [NSError errorWithDomain:NSURLErrorDomain code:[((NSHTTPURLResponse *)response) statusCode] userInfo:nil], YES);
        }
        CFRunLoopStop(CFRunLoopGetCurrent());
        [self done];
    }
}
```

Thanks!

**Comment by Igor-Palaguta** [comment]
Can't understand where in this sample cached image is sent to completion block. As I see just cancelBlock is called in cancelInternal. Please can you assist. Does this code work as expected?

**Comment by bpoplauschi** [comment]
304 means the image did not change and this happens when you already have the image, so there is no point in downloading it again.

**Comment by mythodeia** [comment]
in the ```downloadImageWithURL``` method inside the ```SDWebImageManager.m``` file
the following is performed:
```
operation.cacheOperation = [self.imageCache queryDiskCacheForKey:key done:^(UIImage *image, SDImageCacheType cacheType) {
```
before calling the ```downloadImageWithURL``` method

**Comment by dreampiggy** [comment]
This one is misunderstading to most of use case. If you need to use with `304` status code. You should use `SDWebImageDownloaderUseNSURLCache` options. Or you should use `SDWebImageRefreshCached`.

We default use `NSURLRequestReloadIgnoringLocalCacheData`, which means even the server response a `ETag`, we do not cache that into anywhere. It just disappear. So even if you specify `If-Modified-Since` or `If-Match-None`and server response a `304` code. You have no way to find the cache files. So that this use case can't work.

If you provide `SDWebImageDownloaderUseNSURLCache`. NSURLSession will handler all of this for us. Actually, if the `Last-Modified-Date` not reach. NSURLSession will directlly callback a data cached by them without any network request. So you can get the call immediately.

Currently we directlly cancel the request when the status code is `304` and do not call any completion block. This is not work as you want(We have no place to find the cache if this case hit). So we drop this behavior and actually pass the response like valid status code.
