### ISSUE TITLE
Images not showing in TableViewCells until it scroll-down

### ISSUE THREAD

**Issue by 0m15** [SDWebImage/SDWebImage#9]
First, thanks for this great project.

I'm facing an Issue occuring when I use UIImageView+WebCache category in a TableViewCell.

The issue is that first cells of the TableView are displaying the placeholder image and not the remote image (even if it's cached), until I scroll up or down the TableView itself.

The problem is that, when I have few cells I can't display any Image but only the placeholder.

Are there any workaround? Note that, when not in a TableView context the remote image is loaded correctly.

**Comment by hilalbaig** [comment]
Assign a placeholder image properly.. issue with me was with wrong image extension that doesn't match with each other i.e. placeholder.jpeg and palceholder@2x.jpg

**Comment by rodrigoruiz** [comment]
I'm seeing the same problem and not even using SDWebImage (I'm using my own `setImageFromLocalURL:`).

Did anyone manage to solve this issue?

**Comment by JPROFFICIAL** [comment]
Although this issue is closed, I had found the same exact issues as the people above, and was unable to use a `placeholderImg` because I was using the `SDWebImageManager.sharedManager().downloadImageWithURL` call.

I was making the `UIImageView.image = nil` in `cellReuse`, and calling `setNeedsLayout - layoutIfNeeded` after the image loaded using that block.

The solution for me was: In the parameters of the above `downloadImageWithURL` call  -> add `SDWebImageOptions.AvoidAutoSetImage` to the `options` parameter. 

Now all of the images load as expected.

Hope this helps someone! Thx so much to the team at SDWebImage for this great lib.

**Comment by habibghantous** [comment]
hello, i am using SDWebImage in a collectionView, but i am getting the first batch of thumbs correctly, and when i scroll down the thumbs are empty for some reason here my code:

    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let imageIndex = indexPath.row
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! PhotoCell
        DispatchQueue.global(qos: .userInitiated).async {
            DataManager.sharedInstance.getThumbUrlAt(categoryIndex: self.categoryIndex, imageIndex: imageIndex) {
                image in
                DispatchQueue.main.async {
                    if let loadedImageCell = collectionView.cellForItem(at: indexPath) as? PhotoCell {
                        loadedImageCell.imageView.sd_setImage(with: URL(string: image), placeholderImage: UIImage(named: "placeholder.png"))
                        
                        cell.layoutIfNeeded()
                    }
                }
            }
        }
        cell.imageView.layer.cornerRadius = 6
        cell.imageView.layer.masksToBounds = true

        cell.layer.shadowColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.5).cgColor
        cell.layer.shadowOpacity = 0.5
        cell.layer.shadowRadius = 3
        cell.layer.shadowOffset = CGSize(width: 0, height: 0)
        cell.layer.shadowPath = UIBezierPath(roundedRect: cell.bounds, cornerRadius: 6).cgPath
        
        return cell
    }

**Comment by dreampiggy** [comment]
Your code seems contains two async operation, which means when the cell is reused, it can not be set to a correct state immediately.

Remember that `cellFotItem` will be called each time you scroll and you should reset all the correct state for that cell(Because it be resued from another cell instance and the state is not sync with the current item). So it's better to keep the data model firstlly in your viewController or viewModel, then just use `sd_setImage`. `sd_setImage` will immediately reset the image to placeholder and then check cache or downloader, which keep the correct state.
