### ISSUE TITLE
Wrong images loaded in UICollectionViewCell

### ISSUE THREAD

**Issue by GBoyadzhiev** [SDWebImage/SDWebImage#968]
Hello, 

I am using the SDWebImage in an app I am working on and I am happy to say that it works like a charm. I have one problem though. I am using the UIImageView+WebCache category to load thumbnail from URLs on UICollectionViewCells and when I scroll fast upwards and downwards in rare occasions I notice that wrong thumbnails are being loaded on some cells (thumbnails from a different position in the collection view). 

Has someone experienced that issue?

**Comment by namanhams** [comment]
Sorry to reopen this, but i don't quite understand what's causes this issue.
When a cell is reused, it will load another image on its imageView, using sd_setImageXXX method. 
Calling sd_setImageXXX will internally call sd_cancelCurrentImageLoad.
So why do i need to cancel the image loading myself ? 

Also this issue seems not happen on UITableView. Only UICollectionView.

**Comment by KirylBelasheuski** [comment]
Simple adding below code helped me.
```
- (void)prepareForReuse {
    [super prepareForReuse];
    [self.imageView sd_cancelCurrentImageLoad];
}
```
Thank you @ianb821

**Comment by mahesha-arkenea** [comment]
This code is awesome....the above one worked for me too.

**Comment by NikunjGangani** [comment]
@KirylBelasheuski Thank you

**Comment by odlar** [comment]
thanks bensie and KirylBelasheuski,i had solve it

**Comment by ilyanengen** [comment]
SWIFT 4
Before setting new image to imageView add:

**cell.imageView.sd_currentDownloadTask?.cancel()**
